In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive

drive.mount('/content/drive')

# 定义你的文件路径 (请根据你实际的 Drive 文件夹结构修改这里的路径)
# 假设你把文件放在了 "ECE1513_Project/data" 文件夹下
traffic_data_path = '/content/drive/MyDrive/ECE1513_Project/Data/svc_raw_data_speed_2020_2024.csv'

# 加载数据 (先读取一部分看看，避免大文件直接撑爆内存)
# 这里用 nrows=5000 先试水，确认路径正确且数据能正常读取
df_traffic = pd.read_csv(traffic_data_path, nrows=5000)
# df_weather = pd.read_csv(weather_data_path, nrows=5000)

print("Traffic Data Shape:", df_traffic.shape)
display(df_traffic.head())

Mounted at /content/drive
Traffic Data Shape: (5000, 23)

,id,count_id,location_name,longitude,latitude,centreline_id,time_start,time_end,direction,vol_1_19kph,...,vol_36_40kph,vol_41_45kph,vol_46_50kph,vol_51_55kph,vol_56_60kph,vol_61_65kph,vol_66_70kph,vol_71_75kph,vol_76_80kph,vol_81_160kph
0,3953826,2825424,Cherrywood Ave: Maplewood Ave - Valewood Ave,-79.428465,43.686135,8534,2020-01-15 15:00:00,2020-01-15 15:15:00,NB,1,...,0,0,0,0,0,0,0,0,0,0
1,3948577,2825226,Viewmount Ave: Shermount Ave - Viewmount Park Trl,-79.438725,43.708139,30063812,2020-01-14 22:45:00,2020-01-14 23:00:00,EB,0,...,1,0,1,0,0,0,0,0,0,0
2,3948578,2825226,Viewmount Ave: Shermount Ave - Viewmount Park Trl,-79.438725,43.708139,30063812,2020-01-14 23:00:00,2020-01-14 23:15:00,EB,0,...,0,0,0,0,0,0,0,1,0,0
3,3948579,2825226,Viewmount Ave: Shermount Ave - Viewmount Park Trl,-79.438725,43.708139,30063812,2020-01-14 23:15:00,2020-01-14 23:30:00,EB,0,...,1,1,0,0,0,0,0,0,0,0
4,3948580,2825226,Viewmount Ave: Shermount Ave - Viewmount Park Trl,-79.438725,43.708139,30063812,2020-01-14 23:30:00,2020-01-14 23:45:00,EB,0,...,3,0,0,0,0,0,0,0,0,0

In [ ]:
import requests
import time
import random
import os
from google.colab import drive

# 1. 挂载 Google Drive 到 Colab
# 运行这行代码时，Colab 会弹出一个窗口请求访问你的 Google Drive，请点击允许。
drive.mount('/content/drive')

# 2. 设置保存路径为你的 Google Drive 中的专属文件夹
# 这样不仅找得到，而且就算 Colab 掉线数据也不会丢
save_dir = '/content/drive/MyDrive/ECE_1513/Data/weather_data_toronto_city_center/raw'

# 检查 Google Drive 里有没有这个文件夹，没有就自动建一个
if not os.path.exists(save_dir):
    os.makedirs(save_dir)
    print(f"📁 已在 Google Drive 创建文件夹: {save_dir}")
else:
    print(f"📁 文件夹已存在，数据将直接保存至: {save_dir}")

# 环境部批量下载接口
base_url = "https://climate.weather.gc.ca/climate_data/bulk_data_e.html"

# 请求头
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Connection": "keep-alive"
}

climate_id = "6158359"
years = [2020,2021,2022,2023,2024,2025,2026]

print("\n🚀 开始下载数据并直接存入 Google Drive...")

for year in years:
    for month in range(1, 13):
        print(f"正在请求 {year}年 {month:02d}月 的数据...")

        params = {
            "format": "csv",
            "climate_id": climate_id,
            "Year": year,
            "Month": month,
            "Day": 1,
            "time": "LST",
            "timeframe": 1,
            "submit": "Download Data"
        }

        filename = os.path.join(save_dir, f"weather_hourly_{climate_id}_{year}_{month:02d}.csv")

        try:
            response = requests.get(base_url, headers=headers, params=params, timeout=20)

            if response.status_code == 200:
                if response.text.strip().lower().startswith("<!doctype html>"):
                    print(f"❌ 警告：可能请求过快被限制了。")
                    time.sleep(10)
                    continue

                with open(filename, "wb") as f:
                    f.write(response.content)
                print(f"✅ {year}年 {month:02d}月 下载成功！")

            else:
                print(f"❌ 请求失败，状态码: {response.status_code}")

        except Exception as e:
            print(f"❌ 网络异常: {e}")

        time.sleep(random.uniform(2.0, 4.0))

print(f"\n🎉 全部下载完毕！请在 Colab 左侧的文件栏，或者直接打开网页版 Google Drive 查看 'Weather_Data_Archive' 文件夹。")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
📁 已在 Google Drive 创建文件夹: /content/drive/MyDrive/ECE_1513/Data/weather_data_toronto_city_center/raw

🚀 开始下载数据并直接存入 Google Drive...
正在请求 2020年 01月 的数据...
✅ 2020年 01月 下载成功！
正在请求 2020年 02月 的数据...
✅ 2020年 02月 下载成功！
正在请求 2020年 03月 的数据...
✅ 2020年 03月 下载成功！
正在请求 2020年 04月 的数据...
✅ 2020年 04月 下载成功！
正在请求 2020年 05月 的数据...
✅ 2020年 05月 下载成功！
正在请求 2020年 06月 的数据...
✅ 2020年 06月 下载成功！
正在请求 2020年 07月 的数据...
✅ 2020年 07月 下载成功！
正在请求 2020年 08月 的数据...
✅ 2020年 08月 下载成功！
正在请求 2020年 09月 的数据...
✅ 2020年 09月 下载成功！
正在请求 2020年 10月 的数据...
✅ 2020年 10月 下载成功！
正在请求 2020年 11月 的数据...
✅ 2020年 11月 下载成功！
正在请求 2020年 12月 的数据...
✅ 2020年 12月 下载成功！
正在请求 2021年 01月 的数据...
✅ 2021年 01月 下载成功！
正在请求 2021年 02月 的数据...
✅ 2021年 02月 下载成功！
正在请求 2021年 03月 的数据...
✅ 2021年 03月 下载成功！
正在请求 2021年 04月 的数据...
✅ 2021年 04月 下载成功！
正在请求 2021年 05月 的数据...
✅ 2021年 05月 下载成功！
正在请求 2021年 06月 的数据...
✅ 2021年 06月 下载成功！
正在请求 2021年 07月 的数据...
✅ 2021年 07月 下载成功！
正在请求 2021年 08月 的数据...
✅ 2021年 08月 下载成功！
正在请求 2021年 09月 的数据...
✅ 2021年 09月 下载成功！
正在请求 2021年 10月 的数据...
✅ 2021年 10月 下载成功！
正在请求 2021年 11月 的数据...
✅ 2021年 11月 下载成功！
正在请求 2021年 12月 的数据...
✅ 2021年 12月 下载成功！
正在请求 2022年 01月 的数据...
✅ 2022年 01月 下载成功！
正在请求 2022年 02月 的数据...
✅ 2022年 02月 下载成功！
正在请求 2022年 03月 的数据...
✅ 2022年 03月 下载成功！
正在请求 2022年 04月 的数据...
✅ 2022年 04月 下载成功！
正在请求 2022年 05月 的数据...
✅ 2022年 05月 下载成功！
正在请求 2022年 06月 的数据...
✅ 2022年 06月 下载成功！
正在请求 2022年 07月 的数据...
✅ 2022年 07月 下载成功！
正在请求 2022年 08月 的数据...
✅ 2022年 08月 下载成功！
正在请求 2022年 09月 的数据...
✅ 2022年 09月 下载成功！
正在请求 2022年 10月 的数据...
✅ 2022年 10月 下载成功！
正在请求 2022年 11月 的数据...
✅ 2022年 11月 下载成功！
正在请求 2022年 12月 的数据...
✅ 2022年 12月 下载成功！
正在请求 2023年 01月 的数据...
✅ 2023年 01月 下载成功！
正在请求 2023年 02月 的数据...
✅ 2023年 02月 下载成功！
正在请求 2023年 03月 的数据...
✅ 2023年 03月 下载成功！
正在请求 2023年 04月 的数据...
✅ 2023年 04月 下载成功！
正在请求 2023年 05月 的数据...
✅ 2023年 05月 下载成功！
正在请求 2023年 06月 的数据...
✅ 2023年 06月 下载成功！
正在请求 2023年 07月 的数据...
✅ 2023年 07月 下载成功！
正在请求 2023年 08月 的数据...
✅ 2023年 08月 下载成功！
正在请求 2023年 09月 的数据...
✅ 2023年 09月 下载成功！
正在请求 2023年 10月 的数据...
✅ 2023年 10月 下载成功！
正在请求 2023年 11月 的数据...
✅ 2023年 11月 下载成功！
正在请求 2023年 12月 的数据...
✅ 2023年 12月 下载成功！
正在请求 2024年 01月 的数据...
✅ 2024年 01月 下载成功！
正在请求 2024年 02月 的数据...
✅ 2024年 02月 下载成功！
正在请求 2024年 03月 的数据...
✅ 2024年 03月 下载成功！
正在请求 2024年 04月 的数据...
✅ 2024年 04月 下载成功！
正在请求 2024年 05月 的数据...
✅ 2024年 05月 下载成功！
正在请求 2024年 06月 的数据...
✅ 2024年 06月 下载成功！
正在请求 2024年 07月 的数据...
✅ 2024年 07月 下载成功！
正在请求 2024年 08月 的数据...
✅ 2024年 08月 下载成功！
正在请求 2024年 09月 的数据...
✅ 2024年 09月 下载成功！
正在请求 2024年 10月 的数据...
✅ 2024年 10月 下载成功！
正在请求 2024年 11月 的数据...
✅ 2024年 11月 下载成功！
正在请求 2024年 12月 的数据...
✅ 2024年 12月 下载成功！
正在请求 2025年 01月 的数据...
✅ 2025年 01月 下载成功！
正在请求 2025年 02月 的数据...
✅ 2025年 02月 下载成功！
正在请求 2025年 03月 的数据...
✅ 2025年 03月 下载成功！
正在请求 2025年 04月 的数据...
✅ 2025年 04月 下载成功！
正在请求 2025年 05月 的数据...
✅ 2025年 05月 下载成功！
正在请求 2025年 06月 的数据...
✅ 2025年 06月 下载成功！
正在请求 2025年 07月 的数据...
✅ 2025年 07月 下载成功！
正在请求 2025年 08月 的数据...
✅ 2025年 08月 下载成功！
正在请求 2025年 09月 的数据...
✅ 2025年 09月 下载成功！
正在请求 2025年 10月 的数据...
✅ 2025年 10月 下载成功！
正在请求 2025年 11月 的数据...
✅ 2025年 11月 下载成功！
正在请求 2025年 12月 的数据...
✅ 2025年 12月 下载成功！
正在请求 2026年 01月 的数据...
✅ 2026年 01月 下载成功！
正在请求 2026年 02月 的数据...
✅ 2026年 02月 下载成功！
正在请求 2026年 03月 的数据...
✅ 2026年 03月 下载成功！
正在请求 2026年 04月 的数据...
✅ 2026年 04月 下载成功！
正在请求 2026年 05月 的数据...
✅ 2026年 05月 下载成功！
正在请求 2026年 06月 的数据...
✅ 2026年 06月 下载成功！
正在请求 2026年 07月 的数据...
✅ 2026年 07月 下载成功！
正在请求 2026年 08月 的数据...
✅ 2026年 08月 下载成功！
正在请求 2026年 09月 的数据...
✅ 2026年 09月 下载成功！
正在请求 2026年 10月 的数据...
✅ 2026年 10月 下载成功！
正在请求 2026年 11月 的数据...
✅ 2026年 11月 下载成功！
正在请求 2026年 12月 的数据...
✅ 2026年 12月 下载成功！

🎉 全部下载完毕！请在 Colab 左侧的文件栏，或者直接打开网页版 Google Drive 查看 'Weather_Data_Archive' 文件夹。

In [ ]:
import pandas as pd
import glob
import os

# 1. 定义你的 Google Drive 文件夹路径
folder_path = '/content/drive/MyDrive/ECE1513_Project/Data/weather_data_toronto_city_center/raw'

# 获取文件夹下所有逐小时天气的 CSV 文件路径
# 确保只匹配我们刚才下载的格式
all_files = glob.glob(os.path.join(folder_path, "weather_hourly_*.csv"))

print(f"🔍 找到了 {len(all_files)} 个气象数据文件，开始合并...")

# 2. 物理合并：读取所有文件并拼接成一个庞大的 DataFrame
df_list = []
for file in all_files:
    # 环境部的数据前几行往往是气象站的基础信息，真实的表头通常在第 16 行左右（Colab 中 index 为 16）
    # 但我们刚才用的 bulk_data_e 接口通常会自动处理好，这里直接读即可，如果报错可以加上 skiprows=16
    temp_df = pd.read_csv(file, low_memory=False)
    df_list.append(temp_df)

# 将 24 个月的 DataFrame 拼接到一起
raw_merged_df = pd.concat(df_list, ignore_index=True)

# 将未清洗的合并版原始数据保存为一个完整的 CSV，作为物理备份
merged_csv_path = os.path.join(folder_path, "merged_weather_2020_2026_raw.csv")
raw_merged_df.to_csv(merged_csv_path, index=False)
print(f"💾 原始合并文件已保存至: {merged_csv_path}")

🔍 找到了 74 个气象数据文件，开始合并...
💾 原始合并文件已保存至: /content/drive/MyDrive/ECE1513_Project/Data/weather_data_toronto_city_center/raw/merged_weather_2020_2026_raw.csv
🧹 开始清洗 DataFrame，提取核心交通气象特征...

✨ 清洗完成！干净的 DataFrame 预览：

,Date/Time (LST),Year,Month,Day,Time (LST),Temp (°C),Wind Spd (km/h),Visibility (km),Rel Hum (%)
0,2020-01-01 00:00:00,2020,1,1,00:00,0.2,35.0,16.1,75.0
1,2020-01-01 01:00:00,2020,1,1,01:00,0.1,34.0,16.1,74.0
2,2020-01-01 02:00:00,2020,1,1,02:00,0.0,34.0,16.1,75.0
3,2020-01-01 03:00:00,2020,1,1,03:00,-0.2,32.0,16.1,74.0
4,2020-01-01 04:00:00,2020,1,1,04:00,-0.2,28.0,16.1,75.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54024 entries, 0 to 54023
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date/Time (LST)  54024 non-null  datetime64[ns]
 1   Year             54024 non-null  int64
 2   Month            54024 non-null  int64
 3   Day              54024 non-null  int64
 4   Time (LST)       54024 non-null  object
 5   Temp (°C)        54024 non-null  float64
 6   Wind Spd (km/h)  54024 non-null  float64
 7   Visibility (km)  54024 non-null  float64
 8   Rel Hum (%)      54024 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(3), object(1)
memory usage: 3.7+ MB

None

In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive

# 1. 确保 Google Drive 已经挂载 (如果当前 session 已经挂载过，这行不会有副作用)
drive.mount('/content/drive')

# 2. 精确配置你的输入和输出路径
input_path = '/content/drive/MyDrive/ECE1513_Project/Data/weather_data_toronto_city_center/merged_weather_2020_2026_raw.csv'
output_path = '/content/drive/MyDrive/ECE1513_Project/Data/weather_data_toronto_city_center/merged_weather_2020_2026_processed.csv'

print(f"📥 正在读取原始气象数据...\n路径: {input_path}")
# low_memory=False 防止 Pandas 在猜测列数据类型时报警告
raw_df = pd.read_csv(input_path, low_memory=False)

print("🧹 开始执行特征清洗与工程...")

# 3. 筛选核心列 (匹配真实表头)
cols_to_keep = [
    'Date/Time (LST)', 'Year', 'Month', 'Day', 'Time (LST)',
    'Temp (°C)', 'Precip. Amount (mm)', 'Wind Spd (km/h)',
    'Wind Dir (10s deg)', 'Visibility (km)', 'Rel Hum (%)', 'Weather'
]
clean_df = raw_df[[col for col in cols_to_keep if col in raw_df.columns]].copy()

# 4. 时间轴标准化
# 这一步对于后续与交通流量数据做时间戳对齐 (Join) 至关重要
clean_df['Date/Time (LST)'] = pd.to_datetime(clean_df['Date/Time (LST)'])
clean_df = clean_df.sort_values(by='Date/Time (LST)').reset_index(drop=True)

# 5. 处理连续型数值缺失 (前向填充)
continuous_cols = ['Temp (°C)', 'Wind Spd (km/h)', 'Visibility (km)', 'Rel Hum (%)', 'Wind Dir (10s deg)']
for col in continuous_cols:
    if col in clean_df.columns:
        clean_df[col] = clean_df[col].ffill()

# 6. 处理降水量缺失 (填 0)
if 'Precip. Amount (mm)' in clean_df.columns:
    clean_df['Precip. Amount (mm)'] = clean_df['Precip. Amount (mm)'].fillna(0)

# 7. 【特征转换】风向周期性编码 (Sin / Cos)
if 'Wind Dir (10s deg)' in clean_df.columns:
    wind_rad = clean_df['Wind Dir (10s deg)'] * 10 * (np.pi / 180)
    clean_df['Wind_Sin'] = np.sin(wind_rad)
    clean_df['Wind_Cos'] = np.cos(wind_rad)
    clean_df = clean_df.drop(columns=['Wind Dir (10s deg)'])

# 8. 【特征转换】天气状态提取 (One-Hot)
# 这些布尔值特征对路面湿滑度和短时拥堵往往有最直接的刺激作用
if 'Weather' in clean_df.columns:
    clean_df['is_raining'] = clean_df['Weather'].str.contains('Rain|Drizzle', case=False, na=False).astype(int)
    clean_df['is_snowing'] = clean_df['Weather'].str.contains('Snow|Ice', case=False, na=False).astype(int)
    clean_df['is_foggy'] = clean_df['Weather'].str.contains('Fog|Mist', case=False, na=False).astype(int)
    clean_df = clean_df.drop(columns=['Weather'])

print("\n✨ 特征工程完成！模型可以直接食用的 DataFrame 预览：")
display(clean_df.head())
print("\n数据基本信息：")
display(clean_df.info())

# 9. 导出为 Processed CSV
print(f"\n💾 正在保存处理后的数据到...\n{output_path}")
# index=False 确保不会生成无用的 Unnamed: 0 索引列
clean_df.to_csv(output_path, index=False)
print("✅ 保存成功！")

Mounted at /content/drive
📥 正在读取原始气象数据...
路径: /content/drive/MyDrive/ECE1513_Project/Data/weather_data_toronto_city_center/merged_weather_2020_2026_raw.csv
🧹 开始执行特征清洗与工程...

✨ 特征工程完成！模型可以直接食用的 DataFrame 预览：

,Date/Time (LST),Year,Month,Day,Time (LST),Temp (°C),Precip. Amount (mm),Wind Spd (km/h),Visibility (km),Rel Hum (%),Wind_Sin,Wind_Cos,is_raining,is_snowing,is_foggy
0,2020-01-01 00:00:00,2020,1,1,00:00,0.2,0.0,35.0,16.1,75.0,-0.939693,-0.34202,0,0,0
1,2020-01-01 01:00:00,2020,1,1,01:00,0.1,0.0,34.0,16.1,74.0,-0.939693,-0.34202,0,0,0
2,2020-01-01 02:00:00,2020,1,1,02:00,0.0,0.0,34.0,16.1,75.0,-0.939693,-0.34202,0,0,0
3,2020-01-01 03:00:00,2020,1,1,03:00,-0.2,0.0,32.0,16.1,74.0,-0.939693,-0.34202,0,0,0
4,2020-01-01 04:00:00,2020,1,1,04:00,-0.2,0.0,28.0,16.1,75.0,-0.939693,-0.34202,0,1,0

数据基本信息：
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54024 entries, 0 to 54023
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date/Time (LST)      54024 non-null  datetime64[ns]
 1   Year                 54024 non-null  int64
 2   Month                54024 non-null  int64
 3   Day                  54024 non-null  int64
 4   Time (LST)           54024 non-null  object
 5   Temp (°C)            54024 non-null  float64
 6   Precip. Amount (mm)  54024 non-null  float64
 7   Wind Spd (km/h)      54024 non-null  float64
 8   Visibility (km)      54024 non-null  float64
 9   Rel Hum (%)          54024 non-null  float64
 10  Wind_Sin             54024 non-null  float64
 11  Wind_Cos             54024 non-null  float64
 12  is_raining           54024 non-null  int64
 13  is_snowing           54024 non-null  int64
 14  is_foggy             54024 non-null  int64
dtypes: datetime64[ns](1), float64(7), int64(6), object(1)
memory usage: 6.2+ MB

None

💾 正在保存处理后的数据到...
/content/drive/MyDrive/ECE1513_Project/Data/weather_data_toronto_city_center/merged_weather_2020_2026_processed.csv
✅ 保存成功！

In [ ]:
import pandas as pd
import numpy as np
import os
from google.colab import drive

# 1. 挂载 Google Drive
drive.mount('/content/drive')

# 2. 设置输入输出路径
project_dir = '/content/drive/MyDrive/ECE1513_Project/Data/traffic_data'
if not os.path.exists(project_dir):
    os.makedirs(project_dir)

# 这一次，我们只需要 Speed 这一张表！
speed_data_path = os.path.join(project_dir, 'svc_raw_data_speed_2020_2024.csv')
output_traffic_path = os.path.join(project_dir, 'clean_traffic_2020_2024.csv')

print("📥 正在读取交通速度特征数据...")
speed_cols = ['centreline_id', 'location_name', 'longitude', 'latitude', 'time_start', 'time_end', 'direction',
              'vol_1_19kph', 'vol_20_25kph', 'vol_26_30kph', 'vol_31_35kph', 'vol_36_40kph', 'vol_41_45kph',
              'vol_46_50kph', 'vol_51_55kph', 'vol_56_60kph', 'vol_61_65kph', 'vol_66_70kph', 'vol_71_75kph',
              'vol_76_80kph', 'vol_81_160kph']

# 读取数据
df = pd.read_csv(speed_data_path, usecols=speed_cols, low_memory=False)

print("⏳ 标准化时间戳...")
df['time_start'] = pd.to_datetime(df['time_start'])
df['time_end'] = pd.to_datetime(df['time_end'])

print("🧮 正在基于速度区间直接计算 [总车流量] 和 [平均车速]...")
speed_bins = [
    'vol_1_19kph', 'vol_20_25kph', 'vol_26_30kph', 'vol_31_35kph', 'vol_36_40kph',
    'vol_41_45kph', 'vol_46_50kph', 'vol_51_55kph', 'vol_56_60kph', 'vol_61_65kph',
    'vol_66_70kph', 'vol_71_75kph', 'vol_76_80kph', 'vol_81_160kph'
]
midpoints = np.array([10, 22.5, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78, 100])

# 【核心突破 1】：直接把所有速度区间的车辆数加起来，就是 15 分钟总流量！
df['volume_15min'] = df[speed_bins].sum(axis=1)

# 【核心突破 2】：计算加权平均速度
weighted_sum_speed = (df[speed_bins] * midpoints).sum(axis=1)
df['avg_speed_kph'] = np.where(df['volume_15min'] > 0,
                               weighted_sum_speed / df['volume_15min'],
                               np.nan)

print("🧹 正在清理数据结构...")
final_cols = [
    'centreline_id', 'location_name', 'longitude', 'latitude', 'direction',
    'time_start', 'time_end', 'volume_15min', 'avg_speed_kph'
]
clean_traffic_df = df[final_cols].sort_values(by=['centreline_id', 'time_start']).reset_index(drop=True)

# 过滤掉 15 分钟内完全没有车的记录 (因为没车就谈不上拥堵速度)，这能进一步帮你的模型去除噪音
clean_traffic_df = clean_traffic_df[clean_traffic_df['volume_15min'] > 0].reset_index(drop=True)

print(f"\n💾 正在保存至: {output_traffic_path}")
clean_traffic_df.to_csv(output_traffic_path, index=False)

print("\n✨ 交通数据处理完成！这一次绝对有数据了，预览前 5 行：")
display(clean_traffic_df.head())
print(f"\n✅ 成功提取了 {len(clean_traffic_df)} 条有效的速度与流量记录！")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
📥 正在读取交通速度特征数据...
⏳ 标准化时间戳...
🧮 正在基于速度区间直接计算 [总车流量] 和 [平均车速]...
🧹 正在清理数据结构...

💾 正在保存至: /content/drive/MyDrive/ECE1513_Project/Data/traffic_data/clean_traffic_2020_2024.csv

✨ 交通数据处理完成！这一次绝对有数据了，预览前 5 行：

,centreline_id,location_name,longitude,latitude,direction,time_start,time_end,volume_15min,avg_speed_kph
0,199,Donlea Dr: Don Avon Dr - Brentcliffe Rd,-79.361425,43.715225,EB,2022-09-20 00:00:00,2022-09-20 00:15:00,2,38.0
1,199,Donlea Dr: Don Avon Dr - Brentcliffe Rd,-79.361425,43.715225,WB,2022-09-20 00:15:00,2022-09-20 00:30:00,1,33.0
2,199,Donlea Dr: Don Avon Dr - Brentcliffe Rd,-79.361425,43.715225,WB,2022-09-20 00:30:00,2022-09-20 00:45:00,1,43.0
3,199,Donlea Dr: Don Avon Dr - Brentcliffe Rd,-79.361425,43.715225,EB,2022-09-20 01:00:00,2022-09-20 01:15:00,1,33.0
4,199,Donlea Dr: Don Avon Dr - Brentcliffe Rd,-79.361425,43.715225,EB,2022-09-20 01:15:00,2022-09-20 01:30:00,1,43.0

✅ 成功提取了 1737739 条有效的速度与流量记录！

In [ ]:
import pandas as pd
import os
from google.colab import drive

# 1. 挂载 Google Drive
drive.mount('/content/drive')

# 2. 配置文件路径 (请确保路径与你 Drive 里的真实路径完全一致)
base_data_dir = '/content/drive/MyDrive/ECE1513_Project/Data'

# 输入文件路径
weather_path = os.path.join(base_data_dir, 'weather_data_toronto_city_center', 'merged_weather_2020_2026_processed.csv')
traffic_path = os.path.join(base_data_dir, 'traffic_data', 'clean_traffic_2020_2024.csv')

# 最终合并后的输出路径
output_path = os.path.join(base_data_dir, 'final_traffic_weather_merged.csv')

print("📥 正在读取已清洗的天气和交通数据集...")
df_weather = pd.read_csv(weather_path, low_memory=False)
df_traffic = pd.read_csv(traffic_path, low_memory=False)

print(f"📊 数据读取完毕！交通表共有 {len(df_traffic)} 行，天气表共有 {len(df_weather)} 行。")

# 3. 时间轴格式化
print("⏳ 正在统一时间序列格式...")
# 天气时间戳
df_weather['Date/Time (LST)'] = pd.to_datetime(df_weather['Date/Time (LST)'])
# 交通时间戳
df_traffic['time_start'] = pd.to_datetime(df_traffic['time_start'])
df_traffic['time_end'] = pd.to_datetime(df_traffic['time_end'])

# 4. 【核心对齐逻辑】时间戳向下取整 (Time Flooring)
# 将交通表的 time_start (例如 15:15:00) 向下取整到整点 (15:00:00)，存入一个临时匹配列
print("🔗 正在按 [小时] 对齐并合并数据...")
df_traffic['join_time_hour'] = df_traffic['time_start'].dt.floor('h')

# 使用 Left Join (左连接)：保留所有的交通记录，把匹配上的天气特征贴在后面
merged_df = pd.merge(
    df_traffic,
    df_weather,
    left_on='join_time_hour',
    right_on='Date/Time (LST)',
    how='left'
)

# 5. 清理冗余列并处理潜在缺失值
print("🧹 正在清理合并后的表结构...")
# 删掉用来 Join 的临时列以及天气表自带的、与交通表重复的日期列
columns_to_drop = ['join_time_hour', 'Date/Time (LST)', 'Year', 'Month', 'Day', 'Time (LST)']
# 只有当这些列存在时才删除，防止报错
merged_df = merged_df.drop(columns=[col for col in columns_to_drop if col in merged_df.columns])

# 因为交通数据到 2024 年，而天气数据到 2026 年（或者可能某几个小时缺失）
# 对天气特征进行前向填充 (Forward Fill)，确保没有因为连接产生的 NaN 破坏模型训练
weather_features = [
    'Temp (°C)', 'Precip. Amount (mm)', 'Wind Spd (km/h)', 'Visibility (km)',
    'Rel Hum (%)', 'Wind_Sin', 'Wind_Cos', 'is_raining', 'is_snowing', 'is_foggy'
]
# 只对存在的天气特征列进行缺失值填充
for col in weather_features:
    if col in merged_df.columns:
        merged_df[col] = merged_df[col].ffill()

# 6. 保存最终的大表
print(f"\n💾 正在保存最终合并版数据集至:\n{output_path}")
merged_df.to_csv(output_path, index=False)

print("\n✨ 完美合并！最终模型基准表前 5 行预览：")
display(merged_df.head())
print(f"\n✅ 成功生成合并数据集，总行数: {len(merged_df)} 行。")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
📥 正在读取已清洗的天气和交通数据集...
📊 数据读取完毕！交通表共有 1737739 行，天气表共有 54024 行。
⏳ 正在统一时间序列格式...
🔗 正在按 [小时] 对齐并合并数据...
🧹 正在清理合并后的表结构...

💾 正在保存最终合并版数据集至:
/content/drive/MyDrive/ECE1513_Project/Data/final_traffic_weather_merged.csv

✨ 完美合并！最终模型基准表前 5 行预览：

,centreline_id,location_name,longitude,latitude,direction,time_start,time_end,volume_15min,avg_speed_kph,Temp (°C),Precip. Amount (mm),Wind Spd (km/h),Visibility (km),Rel Hum (%),Wind_Sin,Wind_Cos,is_raining,is_snowing,is_foggy
0,199,Donlea Dr: Don Avon Dr - Brentcliffe Rd,-79.361425,43.715225,EB,2022-09-20 00:00:00,2022-09-20 00:15:00,2,38.0,17.6,0.0,18.0,16.1,79.0,-0.939693,0.34202,0,0,0
1,199,Donlea Dr: Don Avon Dr - Brentcliffe Rd,-79.361425,43.715225,WB,2022-09-20 00:15:00,2022-09-20 00:30:00,1,33.0,17.6,0.0,18.0,16.1,79.0,-0.939693,0.34202,0,0,0
2,199,Donlea Dr: Don Avon Dr - Brentcliffe Rd,-79.361425,43.715225,WB,2022-09-20 00:30:00,2022-09-20 00:45:00,1,43.0,17.6,0.0,18.0,16.1,79.0,-0.939693,0.34202,0,0,0
3,199,Donlea Dr: Don Avon Dr - Brentcliffe Rd,-79.361425,43.715225,EB,2022-09-20 01:00:00,2022-09-20 01:15:00,1,33.0,17.0,0.0,17.0,16.1,81.0,-0.939693,0.34202,0,0,0
4,199,Donlea Dr: Don Avon Dr - Brentcliffe Rd,-79.361425,43.715225,EB,2022-09-20 01:15:00,2022-09-20 01:30:00,1,43.0,17.0,0.0,17.0,16.1,81.0,-0.939693,0.34202,0,0,0

✅ 成功生成合并数据集，总行数: 1737739 行。

In [ ]:
import pandas as pd
import os
from google.colab import drive

drive.mount('/content/drive')
dir = '/content/drive/MyDrive/ECE1513_Project/Data/final_traffic_weather_merged.csv'
df = pd.read_csv(dir)
df.head()

Mounted at /content/drive

,centreline_id,location_name,longitude,latitude,direction,time_start,time_end,volume_15min,avg_speed_kph,Temp (°C),Precip. Amount (mm),Wind Spd (km/h),Visibility (km),Rel Hum (%),Wind_Sin,Wind_Cos,is_raining,is_snowing,is_foggy
0,199,Donlea Dr: Don Avon Dr - Brentcliffe Rd,-79.361425,43.715225,EB,2022-09-20 00:00:00,2022-09-20 00:15:00,2,38.0,17.6,0.0,18.0,16.1,79.0,-0.939693,0.34202,0,0,0
1,199,Donlea Dr: Don Avon Dr - Brentcliffe Rd,-79.361425,43.715225,WB,2022-09-20 00:15:00,2022-09-20 00:30:00,1,33.0,17.6,0.0,18.0,16.1,79.0,-0.939693,0.34202,0,0,0
2,199,Donlea Dr: Don Avon Dr - Brentcliffe Rd,-79.361425,43.715225,WB,2022-09-20 00:30:00,2022-09-20 00:45:00,1,43.0,17.6,0.0,18.0,16.1,79.0,-0.939693,0.34202,0,0,0
3,199,Donlea Dr: Don Avon Dr - Brentcliffe Rd,-79.361425,43.715225,EB,2022-09-20 01:00:00,2022-09-20 01:15:00,1,33.0,17.0,0.0,17.0,16.1,81.0,-0.939693,0.34202,0,0,0
4,199,Donlea Dr: Don Avon Dr - Brentcliffe Rd,-79.361425,43.715225,EB,2022-09-20 01:15:00,2022-09-20 01:30:00,1,43.0,17.0,0.0,17.0,16.1,81.0,-0.939693,0.34202,0,0,0

In [ ]:
import pandas as pd

# 1. 配置文件路径（请替换为你 Google Drive 中合并后大表的实际路径）
file_path = '/content/drive/MyDrive/ECE1513_Project/Data/final_traffic_weather_merged.csv'

print("📥 正在读取数据集...")
df = pd.read_csv(file_path, low_memory=False)

# 确保 time_start 是时间格式
df['time_start'] = pd.to_datetime(df['time_start'])

# ---------------------------------------------------------
# 目标 1：计算有多少个唯一的 Location
# ---------------------------------------------------------
unique_locations = df['centreline_id'].nunique()
print(f"\n✅ 数据集中总共有 {unique_locations} 个唯一的路段 (Locations)。")

# ---------------------------------------------------------
# 目标 2：计算每个 Location 拥有多少小时的数据
# ---------------------------------------------------------
print("🧮 正在计算每个路段的有效数据时长 (以小时为单位)...")

# 将 15 分钟级别的时间向下取整到小时级别 (例如 00:15 和 00:30 都变成 00:00)
df['hour_trunc'] = df['time_start'].dt.floor('h')

# 按 centreline_id 和 location_name 分组，统计 [不重复的 hour_trunc] 数量
hours_per_location = df.groupby(['centreline_id', 'location_name'])['hour_trunc'].nunique().reset_index()

# 重命名列名以便阅读
hours_per_location.rename(columns={'hour_trunc': 'total_hours_of_data'}, inplace=True)

# 增加一个辅助列：把小时数换算成“天数” (假设每天24小时都有记录)，让人看得更直观
hours_per_location['approx_days'] = (hours_per_location['total_hours_of_data'] / 24).round(1)

# 按数据量从大到小排序
hours_per_location = hours_per_location.sort_values(by='total_hours_of_data', ascending=False).reset_index(drop=True)

print("\n📊 每个 Location 的数据时长统计 (前 20 名)：")
display(hours_per_location.head(20))

print("\n📉 每个 Location 的数据时长统计 (倒数 10 名)：")
display(hours_per_location.tail(10))

# ---------------------------------------------------------
# 目标 3：全局数据分布概览
# ---------------------------------------------------------
print("\n🔍 数据分布概览：")
print(f"数据量最长的路段拥有：{hours_per_location['total_hours_of_data'].max()} 小时 (约 {hours_per_location['approx_days'].max()} 天) 的数据")
print(f"数据量最短的路段拥有：{hours_per_location['total_hours_of_data'].min()} 小时 (约 {hours_per_location['approx_days'].min()} 天) 的数据")
print(f"中位数数据量为：{hours_per_location['total_hours_of_data'].median()} 小时 (约 {round(hours_per_location['total_hours_of_data'].median()/24, 1)} 天)")

# 把这个统计结果保存下来，写 Report 或做数据探索时可以直接用
summary_path = '/content/drive/MyDrive/ECE1513_Project/Data/location_data_summary.csv'
hours_per_location.to_csv(summary_path, index=False)
print(f"\n💾 详细统计结果已保存至: {summary_path}")

📥 正在读取数据集...

✅ 数据集中总共有 2946 个唯一的路段 (Locations)。
🧮 正在计算每个路段的有效数据时长 (以小时为单位)...

📊 每个 Location 的数据时长统计 (前 20 名)：

,centreline_id,location_name,total_hours_of_data,approx_days
0,7992854,Avenue Rd: Balmoral Ave - Foxbar Rd,1440,60.0
1,8741261,Yonge St: Rosehill Ave - Pleasant Blvd,1344,56.0
2,1139332,Mount Pleasant Rd: Inglewood Dr - Glenrose Ave,1344,56.0
3,8677182,Yonge St: Collier St - Scollard St,1242,51.8
4,7974783,Avenue Rd: Yorkville Ave - Lowther Ave,1200,50.0
5,30118756,Yonge St to Lawton Parkette Trl,1176,49.0
6,14177858,Mount Pleasant Rd: Moore Ave - Beltline Trl,1176,49.0
7,1139103,Oriole Pkwy: Walmsley Blvd - Duggan Ave,1176,49.0
8,7950526,Mount Pleasant Rd: Mount Pleasant Bloor Ramp -...,1176,49.0
9,14018223,Palmerston Ave: Lane N of Robinson St and E of...,547,22.8
10,2820671,Palmerston Blvd: College St - Ulster St,539,22.5
11,1146286,Dufferin St: Florence St - Gordon St,504,21.0
12,30040259,Mount Pleasant Rd: Beltline Trl - Merton St,504,21.0
13,9085006,Dundas St W: Mavety St - Medland St,504,21.0
14,20058417,Jarvis St: Sirman Lane - Maitland St,480,20.0
15,30136814,Palmerston Ave: Lane 2 S of College and E of P...,469,19.5
16,1143401,Ossington Ave: Northumberland St - Leeds St,408,17.0
17,14073184,Dovercourt Rd: Sudbury St - Lane S of Queen an...,408,17.0
18,1146507,Niagara St: Adelaide St W - Mitchell Ave,408,17.0
19,10558391,Ossington Ave: Humbert St - Argyle St,408,17.0

📉 每个 Location 的数据时长统计 (倒数 10 名)：

,centreline_id,location_name,total_hours_of_data,approx_days
2936,8371,Harlton Cres: Haverson Blvd - Silverthorn Ave,20,0.8
2937,911890,Monkton Ave: Meadowvale Dr - Van Dusen Blvd,20,0.8
2938,14311499,Lane N of Dupont and W of Osler,19,0.8
2939,911169,Grenview Blvd N: King Georges Rd - The Kingsway,19,0.8
2940,436693,Beardmore Cres: Foxdale Crt - Cummer Ave,19,0.8
2941,438252,Lanbrooke Ave: Melton Grove St - Endell St,19,0.8
2942,60012845,Cassels Ave: Golfview Ave - Cassels Avenue Pla...,19,0.8
2943,912470,Vickson Crt: The East Mall - Tremont Rd,19,0.8
2944,14063627,Lane W of Dufferin and N of Wallace (id: 14063...,18,0.8
2945,14043125,Lane E of Roncesvalles and N of Pearson (id: 1...,15,0.6

🔍 数据分布概览：
数据量最长的路段拥有：1440 小时 (约 60.0 天) 的数据
数据量最短的路段拥有：15 小时 (约 0.6 天) 的数据
中位数数据量为：72.0 小时 (约 3.0 天)

💾 详细统计结果已保存至: /content/drive/MyDrive/ECE1513_Project/Data/location_data_summary.csv

In [ ]:
import pandas as pd

# 读取合并后的大表
file_path = '/content/drive/MyDrive/ECE1513_Project/Data/final_traffic_weather_merged.csv'
print("📥 正在读取数据集计算损失率...")
df = pd.read_csv(file_path, low_memory=False)
df['time_start'] = pd.to_datetime(df['time_start'])

# 基础统计
total_rows = len(df)
total_locations = df['centreline_id'].nunique()

# 计算每个路段的有效小时数
df['hour_trunc'] = df['time_start'].dt.floor('h')
hours_per_loc = df.groupby('centreline_id')['hour_trunc'].nunique()

def calculate_loss(min_hours, days_label):
    # 找出合格的路段
    valid_locs = hours_per_loc[hours_per_loc >= min_hours].index

    # 过滤数据
    retained_df = df[df['centreline_id'].isin(valid_locs)]
    retained_rows = len(retained_df)
    retained_locations = len(valid_locs)

    # 计算损失率
    lost_rows = total_rows - retained_rows
    lost_locs = total_locations - retained_locations

    row_loss_pct = (lost_rows / total_rows) * 100
    loc_loss_pct = (lost_locs / total_locations) * 100

    print(f"\n=======================================")
    print(f" 🛑 方案：剔除 {days_label} ({min_hours} 小时) 以下的数据")
    print(f"=======================================")
    print(f"📍 损失路段数: {lost_locs} 个 (占总路段的 {loc_loss_pct:.1f}%) -> 剩余 {retained_locations} 个路段")
    print(f"📊 损失数据行: {lost_rows:,} 行 (占总数据的 {row_loss_pct:.1f}%) -> 剩余 {retained_rows:,} 行")

# 分别计算 3 天 (72小时) 和 7 天 (168小时) 的损失情况
calculate_loss(72, "3 天")
calculate_loss(168, "7 天")

📥 正在读取数据集计算损失率...

=======================================
 🛑 方案：剔除 3 天 (72 小时) 以下的数据
=======================================
📍 损失路段数: 1347 个 (占总路段的 45.7%) -> 剩余 1599 个路段
📊 损失数据行: 454,956 行 (占总数据的 26.2%) -> 剩余 1,282,783 行

=======================================
 🛑 方案：剔除 7 天 (168 小时) 以下的数据
=======================================
📍 损失路段数: 2728 个 (占总路段的 92.6%) -> 剩余 218 个路段
📊 损失数据行: 1,270,795 行 (占总数据的 73.1%) -> 剩余 466,944 行

In [ ]:
import pandas as pd
import numpy as np
import os
from google.colab import drive

# 1. 挂载 Drive 并读取数据
drive.mount('/content/drive')

# 输入文件和输出文件在同一个目录
data_dir = '/content/drive/MyDrive/ECE1513_Project/Data'
input_file = os.path.join(data_dir, 'final_traffic_weather_merged.csv')
output_file = os.path.join(data_dir, 'final_traffic_weather_ml_ready.csv')

print(f"📥 正在读取合并后的数据集...\n路径: {input_file}")
df = pd.read_csv(input_file, low_memory=False)
df['time_start'] = pd.to_datetime(df['time_start'])

# ==========================================
# 步骤 1：质量控制 (剔除数据 < 72 小时的路段)
# ==========================================
print("🧹 正在执行质量控制，剔除有效数据不足 72 小时的路段...")
df['hour_trunc'] = df['time_start'].dt.floor('h')
hours_per_loc = df.groupby('centreline_id')['hour_trunc'].nunique()

valid_centreline_ids = hours_per_loc[hours_per_loc >= 72].index
df = df[df['centreline_id'].isin(valid_centreline_ids)].copy()
df = df.drop(columns=['hour_trunc'])

# ==========================================
# 步骤 2：构建拥堵标签 (Target Variable)
# ==========================================
print("🎯 正在构建相对拥堵标签 (is_congested)...")
# 计算每个路段的第 85 百分位速度，作为自由流速度
df['free_flow_speed'] = df.groupby('centreline_id')['avg_speed_kph'].transform(lambda x: x.quantile(0.85))
# 定义阈值：如果当前速度低于自由流速度的 60%，则标记为 1 (拥堵)，否则为 0
df['is_congested'] = (df['avg_speed_kph'] < (df['free_flow_speed'] * 0.60)).astype(int)
df = df.drop(columns=['free_flow_speed'])

# ==========================================
# 步骤 3：构建时间特征 (Temporal Features)
# ==========================================
print("⏰ 正在提取周期性时间特征...")
df['hour_of_day'] = df['time_start'].dt.hour
df['day_of_week'] = df['time_start'].dt.dayofweek
df['is_weekend'] = df['day_of_week'].apply(lambda x: 1 if x >= 5 else 0)

# ==========================================
# 步骤 4：构建滞后特征 (Lag Features)
# ==========================================
print("⏪ 正在构建历史滞后特征 (Lag 1 & Lag 2)...")
df = df.sort_values(by=['centreline_id', 'time_start']).reset_index(drop=True)

df['lag_1_speed'] = df.groupby('centreline_id')['avg_speed_kph'].shift(1)
df['lag_1_vol'] = df.groupby('centreline_id')['volume_15min'].shift(1)
df['lag_2_speed'] = df.groupby('centreline_id')['avg_speed_kph'].shift(2)
df['lag_2_vol'] = df.groupby('centreline_id')['volume_15min'].shift(2)

# 清理因为位移操作产生的 NaN 行 (每个路段的前两条记录)
df = df.dropna(subset=['lag_1_speed', 'lag_2_speed']).reset_index(drop=True)

# ==========================================
# 步骤 5：严格的时间感知切分 (标记 split 标签)
# ==========================================
print("✂️ 正在标记 Train/Val/Test 集合 (70% / 15% / 15%)...")

def time_aware_split(group):
    n = len(group)
    train_end = int(n * 0.7)
    val_end = int(n * 0.85)

    # 默认全部初始化为 train，然后覆盖 val 和 test 区域
    group['split'] = 'train'
    group.iloc[train_end:val_end, group.columns.get_loc('split')] = 'val'
    group.iloc[val_end:, group.columns.get_loc('split')] = 'test'
    return group

df = df.groupby('centreline_id', group_keys=False).apply(time_aware_split)

# ==========================================
# 步骤 6：导出单一完整文件
# ==========================================
print(f"\n💾 正在保存完整特征数据集至:\n{output_file}")
df.to_csv(output_file, index=False)

# 打印最终统计信息
train_count = len(df[df['split'] == 'train'])
val_count = len(df[df['split'] == 'val'])
test_count = len(df[df['split'] == 'test'])

print("\n🎉 ML Ready Data 准备就绪！")
print(f"👉 包含 {df['centreline_id'].nunique()} 个有效路段")
print(f"👉 训练集 (train) 占比/行数: {train_count/len(df):.1%} ({train_count:,} 行)")
print(f"👉 验证集 (val) 占比/行数: {val_count/len(df):.1%} ({val_count:,} 行)")
print(f"👉 测试集 (test) 占比/行数: {test_count/len(df):.1%} ({test_count:,} 行)")
print(f"🔥 全局拥堵样本占比: {df['is_congested'].mean():.2%}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
📥 正在读取合并后的数据集...
路径: /content/drive/MyDrive/ECE1513_Project/Data/final_traffic_weather_merged.csv
🧹 正在执行质量控制，剔除有效数据不足 72 小时的路段...
🎯 正在构建相对拥堵标签 (is_congested)...
⏰ 正在提取周期性时间特征...
⏪ 正在构建历史滞后特征 (Lag 1 & Lag 2)...
✂️ 正在标记 Train/Val/Test 集合 (70% / 15% / 15%)...

/tmp/ipykernel_7143/4228142492.py:77: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby('centreline_id', group_keys=False).apply(time_aware_split)

💾 正在保存完整特征数据集至:
/content/drive/MyDrive/ECE1513_Project/Data/final_traffic_weather_ml_ready.csv

🎉 ML Ready Data 准备就绪！
👉 包含 1599 个有效路段
👉 训练集 (train) 占比/行数: 69.9% (894,906 行)
👉 验证集 (val) 占比/行数: 15.0% (191,887 行)
👉 测试集 (test) 占比/行数: 15.1% (192,792 行)
🔥 全局拥堵样本占比: 2.60%

In [ ]:
# This is the avg_speed_kph prediction block.
# ============================================================
# ECE1513 Project — Baseline Random Forest Model
# Replicates teammate's approach:
#   - Time features (hour, day-of-week encodings)
#   - Lag features (speed & volume lags)
#   - Rolling window features (mean & std)
# ============================================================

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import matplotlib.pyplot as plt
from google.colab import drive

# ── 1. Load Data ─────────────────────────────────────────────
drive.mount('/content/drive')
# file_path = '/content/drive/MyDrive/ECE1513_Project/Data/final_traffic_weather_merged.csv'
file_path = '/content/drive/MyDrive/ECE1513_Project/Data/final_traffic_weather_ml_ready.csv'


df = pd.read_csv(file_path)

# Parse datetime columns
df['time_start'] = pd.to_datetime(df['time_start'])
df['time_end']   = pd.to_datetime(df['time_end'])

# Sort for correct lag/rolling computation
df = df.sort_values(['centreline_id', 'direction', 'time_start']).reset_index(drop=True)

print(f"Total records loaded: {len(df)}")
print(f"Date range: {df['time_start'].min()} to {df['time_start'].max()}")
print(f"Columns: {list(df.columns)}\n")


# ── 2. Time Features ─────────────────────────────────────────
df['hour']       = df['time_start'].dt.hour
df['minute']     = df['time_start'].dt.minute
df['dayofweek']  = df['time_start'].dt.dayofweek   # 0=Mon, 6=Sun
df['month']      = df['time_start'].dt.month
df['is_weekend'] = (df['dayofweek'] >= 5).astype(int)

# Cyclical encoding for hour (captures circular nature: 23h \u2248 0h)
df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)
df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)

# Cyclical encoding for day of week
df['dow_sin'] = np.sin(2 * np.pi * df['dayofweek'] / 7)
df['dow_cos'] = np.cos(2 * np.pi * df['dayofweek'] / 7)


# ── 3. Lag Features ──────────────────────────────────────────
# Group by road segment + direction so lags don't bleed across segments
group_keys = ['centreline_id', 'direction']

# Speed lags: 1, 2, 4, 8 steps back (each step = 15 min)
for lag in [1, 2, 4, 8]:
    df[f'speed_lag_{lag}'] = df.groupby(group_keys)['avg_speed_kph'].shift(lag)

# Volume lags
for lag in [1, 2, 4, 8]:
    df[f'volume_lag_{lag}'] = df.groupby(group_keys)['volume_15min'].shift(lag)


# ── 4. Rolling Window Features ───────────────────────────────
# Windows of 4 steps (1 h) and 8 steps (2 h)
for window in [4, 8]:
    grp = df.groupby(group_keys)

    df[f'speed_roll_mean_{window}'] = (
        grp['avg_speed_kph']
        .transform(lambda x: x.shift(1).rolling(window, min_periods=1).mean())
    )
    df[f'speed_roll_std_{window}'] = (
        grp['avg_speed_kph']
        .transform(lambda x: x.shift(1).rolling(window, min_periods=1).std())
    )
    df[f'volume_roll_mean_{window}'] = (
        grp['volume_15min']
        .transform(lambda x: x.shift(1).rolling(window, min_periods=1).mean())
    )

# 15-min volume used directly (already a feature)
df['volume_15min_feat'] = df['volume_15min']


# ── 5. Define Features & Target ──────────────────────────────
# 定义预测目标为 avg_speed_kph
TARGET = 'avg_speed_kph'

FEATURES = [
    # Location
    'longitude', 'latitude', 'centreline_id',
    # Time
    'hour', 'dayofweek', 'month', 'is_weekend',
    'hour_sin', 'hour_cos', 'dow_sin', 'dow_cos',
    # Weather
    'Temp (°C)', 'Precip. Amount (mm)', 'Wind Spd (km/h)',
    'Visibility (km)', 'Rel Hum (%)',
    'Wind_Sin', 'Wind_Cos',
    'is_raining', 'is_snowing', 'is_foggy',
    # Volume
    'volume_15min_feat',
    # Lag features
    'speed_lag_1', 'speed_lag_2', 'speed_lag_4', 'speed_lag_8',
    'volume_lag_1', 'volume_lag_2', 'volume_lag_4', 'volume_lag_8',
    # Rolling features
    'speed_roll_mean_4', 'speed_roll_mean_8',
    'speed_roll_std_4',  'speed_roll_std_8',
    'volume_roll_mean_4', 'volume_roll_mean_8',
]

# Drop rows with NaN introduced by lag/rolling
df_model = df.dropna(subset=FEATURES + [TARGET]).copy()
print(f"Records after dropping NaN: {len(df_model)}")


# ── 6. Time-Aware Train / Test Split ─────────────────────────
# Use 80% of time range for training, remaining 20% for test
# This prevents temporal data leakage
split_time = df_model['time_start'].quantile(0.80)
# quantile on datetime needs a workaround:
split_time = df_model['time_start'].sort_values().iloc[int(0.80 * len(df_model))]

train_df = df_model[df_model['time_start'] <= split_time]
test_df  = df_model[df_model['time_start'] >  split_time]

print(f"\nTrain size: {len(train_df)}")
print(f"Test size:  {len(test_df)}")
print(f"Train time range: {train_df['time_start'].min()} to {train_df['time_start'].max()}")
print(f"Test time range:  {test_df['time_start'].min()} to  {test_df['time_start'].max()}")

X_train = train_df[FEATURES]
y_train = train_df[TARGET]
X_test  = test_df[FEATURES]
y_test  = test_df[TARGET]


# ── 7. Train Random Forest ───────────────────────────────────
print("\nTraining Random Forest baseline...")

rf_model = RandomForestRegressor(
    n_estimators=100,
    max_depth=None,        # grow full trees
    min_samples_leaf=5,
    n_jobs=-1,             # use all CPU cores
    random_state=42,
)
rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)


# ── 8. Evaluate ──────────────────────────────────────────────
mae  = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2   = r2_score(y_test, y_pred)

print("\n===== Baseline Model Performance =====")
print(f"MAE  : {mae:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"R^2  : {r2:.4f}")


# ── 9. Save Predictions ──────────────────────────────────────
preds_df = test_df[['centreline_id', 'direction', 'time_start', TARGET]].copy()
preds_df['predicted_speed'] = y_pred
preds_df.to_csv('/content/drive/MyDrive/ECE1513_Project/Data/baseline_predictions.csv', index=False)
print("\nSaved predictions to baseline_predictions.csv")


# ── 10. Feature Importance ───────────────────────────────────
importance_df = pd.DataFrame({
    'feature':    FEATURES,
    'importance': rf_model.feature_importances_,
}).sort_values('importance', ascending=False)

print("\nTop 20 important features:")
print(importance_df.head(20).to_string())

importance_df.to_csv(
    '/content/drive/MyDrive/ECE1513_Project/Data/baseline_feature_importance.csv',
    index=False
)
print("\nSaved feature importance to baseline_feature_importance.csv")


# ── 13. Load & Reuse (example) ───────────────────────────────
# To reuse this model in any future notebook, just run:
#
#   import joblib
#   xgb_model = joblib.load('/content/drive/MyDrive/ECE1513_Project/Models/xgb_model.pkl')
#   y_pred = xgb_model.predict(X_test)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Total records loaded: 1279585
Date range: 2020-01-14 00:15:00 to 2024-12-19 23:45:00
Columns: ['centreline_id', 'location_name', 'longitude', 'latitude', 'direction', 'time_start', 'time_end', 'volume_15min', 'avg_speed_kph', 'Temp (°C)', 'Precip. Amount (mm)', 'Wind Spd (km/h)', 'Visibility (km)', 'Rel Hum (%)', 'Wind_Sin', 'Wind_Cos', 'is_raining', 'is_snowing', 'is_foggy', 'is_congested', 'hour_of_day', 'day_of_week', 'is_weekend', 'lag_1_speed', 'lag_1_vol', 'lag_2_speed', 'lag_2_vol', 'split']

KeyboardInterrupt:

In [ ]:
# ============================================================
# ECE1513 Project — XGBoost Regression Model
# Improvements over RF baseline:
#   - Speed deviation feature (fixes leakage)
#   - Deviation-based lags & rolling stats
#   - XGBoost with early stopping
#   - Saves model with joblib
# ============================================================

import pandas as pd
import numpy as np
import joblib
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from google.colab import drive

# ── 1. Load Data ─────────────────────────────────────────────

drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/ECE1513_Project/Data/final_traffic_weather_merged.csv'

df = pd.read_csv(file_path)
df['time_start'] = pd.to_datetime(df['time_start'])
df['time_end']   = pd.to_datetime(df['time_end'])
df = df.sort_values(['centreline_id', 'direction', 'time_start']).reset_index(drop=True)

print(f"Total records loaded: {len(df)}")
print(f"Date range: {df['time_start'].min()} to {df['time_start'].max()}")


# ── 2. Time Features ─────────────────────────────────────────
df['hour']       = df['time_start'].dt.hour
df['minute']     = df['time_start'].dt.minute
df['dayofweek']  = df['time_start'].dt.dayofweek
df['month']      = df['time_start'].dt.month
df['is_weekend'] = (df['dayofweek'] >= 5).astype(int)

df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)
df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)
df['dow_sin']  = np.sin(2 * np.pi * df['dayofweek'] / 7)
df['dow_cos']  = np.cos(2 * np.pi * df['dayofweek'] / 7)


# ── 3. Speed Deviation (leakage fix) ─────────────────────────
# For each road segment + direction + hour + day-of-week,
# compute the historical average speed. Then subtract it.
# This tells the model "is traffic abnormally slow RIGHT NOW?"
# instead of leaking the raw speed value directly into lags.

historical_avg = (
    df.groupby(['centreline_id', 'direction', 'hour', 'dayofweek'])['avg_speed_kph']
    .transform('mean')
)
df['speed_deviation'] = df['avg_speed_kph'] - historical_avg

# Same for volume
historical_vol_avg = (
    df.groupby(['centreline_id', 'direction', 'hour', 'dayofweek'])['volume_15min']
    .transform('mean')
)
df['volume_deviation'] = df['volume_15min'] - historical_vol_avg


# ── 4. Lag Features (on deviation, not raw speed) ────────────
group_keys = ['centreline_id', 'direction']

# Deviation lags — these are the safe, non-leaky version
for lag in [1, 2, 4, 8]:
    df[f'speed_dev_lag_{lag}']  = df.groupby(group_keys)['speed_deviation'].shift(lag)
    df[f'volume_dev_lag_{lag}'] = df.groupby(group_keys)['volume_deviation'].shift(lag)

# Keep raw speed lags too but with a larger minimum gap (lag >= 2)
# lag_1 of raw speed is fine as long as we don't also include roll_mean_1
for lag in [2, 4, 8]:
    df[f'speed_lag_{lag}']  = df.groupby(group_keys)['avg_speed_kph'].shift(lag)
    df[f'volume_lag_{lag}'] = df.groupby(group_keys)['volume_15min'].shift(lag)


# ── 5. Rolling Window Features (on deviation) ─────────────────
for window in [4, 8]:
    grp = df.groupby(group_keys)

    # Rolling mean of deviation — "has it been getting worse recently?"
    df[f'speed_dev_roll_mean_{window}'] = (
        grp['speed_deviation']
        .transform(lambda x: x.shift(1).rolling(window, min_periods=1).mean())
    )
    df[f'speed_dev_roll_std_{window}'] = (
        grp['speed_deviation']
        .transform(lambda x: x.shift(1).rolling(window, min_periods=1).std())
    )
    df[f'volume_dev_roll_mean_{window}'] = (
        grp['volume_deviation']
        .transform(lambda x: x.shift(1).rolling(window, min_periods=1).mean())
    )

    # Raw speed rolling (shifted by 2 to avoid leakage from t-1)
    df[f'speed_roll_mean_{window}'] = (
        grp['avg_speed_kph']
        .transform(lambda x: x.shift(2).rolling(window, min_periods=1).mean())
    )


# ── 6. Historical context features ───────────────────────────
# Give the model direct access to what "normal" looks like
# for this segment/hour/DOW combination
df['hist_avg_speed']  = historical_avg
df['hist_avg_volume'] = historical_vol_avg


# ── 7. Define Features & Target ──────────────────────────────
TARGET = 'avg_speed_kph'

FEATURES = [
    # Location
    'longitude', 'latitude', 'centreline_id',
    # Time
    'hour', 'dayofweek', 'month', 'is_weekend',
    'hour_sin', 'hour_cos', 'dow_sin', 'dow_cos',
    # Weather
    'Temp (°C)', 'Precip. Amount (mm)', 'Wind Spd (km/h)',
    'Visibility (km)', 'Rel Hum (%)',
    'Wind_Sin', 'Wind_Cos',
    'is_raining', 'is_snowing', 'is_foggy',
    # Historical context (what is "normal" here)
    'hist_avg_speed', 'hist_avg_volume',
    # Deviation lags (core non-leaky signal)
    'speed_dev_lag_1', 'speed_dev_lag_2', 'speed_dev_lag_4', 'speed_dev_lag_8',
    'volume_dev_lag_1', 'volume_dev_lag_2', 'volume_dev_lag_4', 'volume_dev_lag_8',
    # Deviation rolling stats
    'speed_dev_roll_mean_4', 'speed_dev_roll_mean_8',
    'speed_dev_roll_std_4',  'speed_dev_roll_std_8',
    'volume_dev_roll_mean_4', 'volume_dev_roll_mean_8',
    # Raw lags (lag >= 2 only)
    'speed_lag_2', 'speed_lag_4', 'speed_lag_8',
    'volume_lag_2', 'volume_lag_4', 'volume_lag_8',
    # Raw rolling (shifted by 2)
    'speed_roll_mean_4', 'speed_roll_mean_8',
    # Raw volume (current interval)
    'volume_15min',
]

df_model = df.dropna(subset=FEATURES + [TARGET]).copy()
print(f"\nRecords after dropping NaN: {len(df_model)}")


# ── 8. Time-Aware Train / Val / Test Split ───────────────────
# 70% train | 10% validation (for early stopping) | 20% test
# Strict time ordering — no shuffling

n = len(df_model)
sorted_df = df_model.sort_values('time_start').reset_index(drop=True)

train_end = int(n * 0.70)
val_end   = int(n * 0.80)

train_df = sorted_df.iloc[:train_end]
val_df   = sorted_df.iloc[train_end:val_end]
test_df  = sorted_df.iloc[val_end:]

print(f"\nTrain size: {len(train_df)}")
print(f"Val size:   {len(val_df)}")
print(f"Test size:  {len(test_df)}")
print(f"Train time range: {train_df['time_start'].min()} to {train_df['time_start'].max()}")
print(f"Test time range:  {test_df['time_start'].min()} to {test_df['time_start'].max()}")

X_train = train_df[FEATURES]
y_train = train_df[TARGET]
X_val   = val_df[FEATURES]
y_val   = val_df[TARGET]
X_test  = test_df[FEATURES]
y_test  = test_df[TARGET]


# ── 9. Train XGBoost ─────────────────────────────────────────
print("\nTraining XGBoost...")

xgb_model = XGBRegressor(
    n_estimators      = 1000,   # high ceiling — early stopping will cut this down
    learning_rate     = 0.05,
    max_depth         = 6,
    min_child_weight  = 5,
    subsample         = 0.8,    # row sampling per tree (reduces overfitting)
    colsample_bytree  = 0.8,    # feature sampling per tree
    reg_alpha         = 0.1,    # L1 regularization
    reg_lambda        = 1.0,    # L2 regularization
    random_state      = 42,
    n_jobs            = -1,
    tree_method       = 'hist', # fast histogram method — good for large datasets
    early_stopping_rounds = 30, # stop if val loss doesn't improve for 30 rounds
    eval_metric       = 'rmse',
)

xgb_model.fit(
    X_train, y_train,
    eval_set=[(X_val, y_val)],
    verbose=50,   # print every 50 rounds
)

print(f"\nBest iteration: {xgb_model.best_iteration}")


# ── 10. Evaluate ─────────────────────────────────────────────
y_pred = xgb_model.predict(X_test)

mae  = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2   = r2_score(y_test, y_pred)

print("\n===== XGBoost Model Performance =====")
print(f"MAE  : {mae:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"R^2  : {r2:.4f}")


# ── 11. Save Model & Predictions ─────────────────────────────
MODEL_PATH = '/content/drive/MyDrive/ECE1513_Project/Models/xgb_model.pkl'
joblib.dump(xgb_model, MODEL_PATH)
print(f"\nSaved model to {MODEL_PATH}")

preds_df = test_df[['centreline_id', 'direction', 'time_start', TARGET]].copy()
preds_df['predicted_speed'] = y_pred
preds_df.to_csv(
    '/content/drive/MyDrive/ECE1513_Project/Data/xgb_predictions.csv',
    index=False
)
print("Saved predictions to xgb_predictions.csv")


# ── 12. Feature Importance ───────────────────────────────────
importance_df = pd.DataFrame({
    'feature':    FEATURES,
    'importance': xgb_model.feature_importances_,
}).sort_values('importance', ascending=False)

print("\nTop 20 important features:")
print(importance_df.head(20).to_string())

importance_df.to_csv(
    '/content/drive/MyDrive/ECE1513_Project/Data/xgb_feature_importance.csv',
    index=False
)
print("\nSaved feature importance to xgb_feature_importance.csv")


# ── 13. Load & Reuse (example) ───────────────────────────────
# To reuse this model in any future notebook, just run:
#
#   import joblib
#   xgb_model = joblib.load('/content/drive/MyDrive/ECE1513_Project/Models/xgb_model.pkl')
#   y_pred = xgb_model.predict(X_test)

Mounted at /content/drive
Total records loaded: 1737739
Date range: 2020-01-14 00:00:00 to 2024-12-19 23:45:00

Records after dropping NaN: 1692667

Train size: 1184866
Val size:   169267
Test size:  338534
Train time range: 2020-01-14 02:00:00 to 2023-06-23 04:15:00
Test time range:  2023-11-02 16:00:00 to 2024-12-19 23:45:00

Training XGBoost...
[0]	validation_0-rmse:10.88187
[50]	validation_0-rmse:3.58241
[100]	validation_0-rmse:3.32183
[150]	validation_0-rmse:3.25391
[200]	validation_0-rmse:3.22942
[250]	validation_0-rmse:3.21475
[300]	validation_0-rmse:3.20439
[350]	validation_0-rmse:3.19578
[400]	validation_0-rmse:3.18979
[450]	validation_0-rmse:3.18481
[500]	validation_0-rmse:3.18072
[550]	validation_0-rmse:3.17773
[600]	validation_0-rmse:3.17587
[650]	validation_0-rmse:3.17319
[700]	validation_0-rmse:3.17069
[750]	validation_0-rmse:3.16854
[800]	validation_0-rmse:3.16722
[850]	validation_0-rmse:3.16570
[900]	validation_0-rmse:3.16462
[950]	validation_0-rmse:3.16342
[999]	validation_0-rmse:3.16230

Best iteration: 996

===== XGBoost Model Performance =====
MAE  : 2.2459
RMSE : 3.4191
R^2  : 0.8910

Saved model to /content/drive/MyDrive/ECE1513_Project/Models/xgb_model.pkl
Saved predictions to xgb_predictions.csv

Top 20 important features:
                   feature  importance
21          hist_avg_speed    0.678652
44       speed_roll_mean_8    0.188056
37             speed_lag_2    0.038395
38             speed_lag_4    0.019084
32   speed_dev_roll_mean_8    0.007606
43       speed_roll_mean_4    0.005337
45            volume_15min    0.004357
31   speed_dev_roll_mean_4    0.003909
22         hist_avg_volume    0.003207
23         speed_dev_lag_1    0.002856
36  volume_dev_roll_mean_8    0.002752
39             speed_lag_8    0.002642
24         speed_dev_lag_2    0.002336
1                 latitude    0.002079
25         speed_dev_lag_4    0.002052
0                longitude    0.001978
40            volume_lag_2    0.001974
41            volume_lag_4    0.001831
5                    month    0.001609
26         speed_dev_lag_8    0.001588

Saved feature importance to xgb_feature_importance.csv

In [ ]:


# ============================================================
# ECE1513 Project — XGBoost Regression Model
# Improvements over RF baseline:
#   - Speed deviation feature (fixes leakage)
#   - Deviation-based lags & rolling stats
#   - XGBoost with early stopping
#   - Saves model with joblib
# ============================================================

import pandas as pd
import numpy as np
import joblib
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from google.colab import drive

# ── 1. Load Data ─────────────────────────────────────────────

drive.mount('/content/drive')

df = pd.read_csv(file_path)
df['time_start'] = pd.to_datetime(df['time_start'])
df['time_end']   = pd.to_datetime(df['time_end'])
df = df.sort_values(['centreline_id', 'direction', 'time_start']).reset_index(drop=True)

print(f"Total records loaded: {len(df)}")
print(f"Date range: {df['time_start'].min()} to {df['time_start'].max()}")


# ── 2. Time Features ─────────────────────────────────────────
df['hour']       = df['time_start'].dt.hour
df['minute']     = df['time_start'].dt.minute
df['dayofweek']  = df['time_start'].dt.dayofweek
df['month']      = df['time_start'].dt.month
df['is_weekend'] = (df['dayofweek'] >= 5).astype(int)

df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)
df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)
df['dow_sin']  = np.sin(2 * np.pi * df['dayofweek'] / 7)
df['dow_cos']  = np.cos(2 * np.pi * df['dayofweek'] / 7)


# ── 3. Speed Deviation (leakage fix) ─────────────────────────
# For each road segment + direction + hour + day-of-week,
# compute the historical average speed. Then subtract it.
# This tells the model "is traffic abnormally slow RIGHT NOW?"
# instead of leaking the raw speed value directly into lags.

historical_avg = (
    df.groupby(['centreline_id', 'direction', 'hour', 'dayofweek'])['avg_speed_kph']
    .transform('mean')
)
df['speed_deviation'] = df['avg_speed_kph'] - historical_avg

# Same for volume
historical_vol_avg = (
    df.groupby(['centreline_id', 'direction', 'hour', 'dayofweek'])['volume_15min']
    .transform('mean')
)
df['volume_deviation'] = df['volume_15min'] - historical_vol_avg


# ── 4. Lag Features (on deviation, not raw speed) ────────────
group_keys = ['centreline_id', 'direction']

# Deviation lags — these are the safe, non-leaky version
for lag in [1, 2, 4, 8]:
    df[f'speed_dev_lag_{lag}']  = df.groupby(group_keys)['speed_deviation'].shift(lag)
    df[f'volume_dev_lag_{lag}'] = df.groupby(group_keys)['volume_deviation'].shift(lag)

# Keep raw speed lags too but with a larger minimum gap (lag >= 2)
# lag_1 of raw speed is fine as long as we don't also include roll_mean_1
for lag in [2, 4, 8]:
    df[f'speed_lag_{lag}']  = df.groupby(group_keys)['avg_speed_kph'].shift(lag)
    df[f'volume_lag_{lag}'] = df.groupby(group_keys)['volume_15min'].shift(lag)


# ── 5. Rolling Window Features (on deviation) ─────────────────
for window in [4, 8]:
    grp = df.groupby(group_keys)

    # Rolling mean of deviation — "has it been getting worse recently?"
    df[f'speed_dev_roll_mean_{window}'] = (
        grp['speed_deviation']
        .transform(lambda x: x.shift(1).rolling(window, min_periods=1).mean())
    )
    df[f'speed_dev_roll_std_{window}'] = (
        grp['speed_deviation']
        .transform(lambda x: x.shift(1).rolling(window, min_periods=1).std())
    )
    df[f'volume_dev_roll_mean_{window}'] = (
        grp['volume_deviation']
        .transform(lambda x: x.shift(1).rolling(window, min_periods=1).mean())
    )

    # Raw speed rolling (shifted by 2 to avoid leakage from t-1)
    df[f'speed_roll_mean_{window}'] = (
        grp['avg_speed_kph']
        .transform(lambda x: x.shift(2).rolling(window, min_periods=1).mean())
    )


# ── 6. Historical context features ───────────────────────────
# Give the model direct access to what "normal" looks like
# for this segment/hour/DOW combination
df['hist_avg_speed']  = historical_avg
df['hist_avg_volume'] = historical_vol_avg


# ── 7. Define Features & Target ──────────────────────────────
TARGET = 'speed_deviation'

FEATURES = [
    # Location
    'longitude', 'latitude', 'centreline_id',
    # Time
    'hour', 'dayofweek', 'month', 'is_weekend',
    'hour_sin', 'hour_cos', 'dow_sin', 'dow_cos',
    # Weather
    'Temp (°C)', 'Precip. Amount (mm)', 'Wind Spd (km/h)',
    'Visibility (km)', 'Rel Hum (%)',
    'Wind_Sin', 'Wind_Cos',
    'is_raining', 'is_snowing', 'is_foggy',
    # Historical context (what is "normal" here)
    'hist_avg_speed', 'hist_avg_volume',
    # Deviation lags (core non-leaky signal)
    'speed_dev_lag_1', 'speed_dev_lag_2', 'speed_dev_lag_4', 'speed_dev_lag_8',
    'volume_dev_lag_1', 'volume_dev_lag_2', 'volume_dev_lag_4', 'volume_dev_lag_8',
    # Deviation rolling stats
    'speed_dev_roll_mean_4', 'speed_dev_roll_mean_8',
    'speed_dev_roll_std_4',  'speed_dev_roll_std_8',
    'volume_dev_roll_mean_4', 'volume_dev_roll_mean_8',
    # Raw lags (lag >= 2 only)
    'speed_lag_2', 'speed_lag_4', 'speed_lag_8',
    'volume_lag_2', 'volume_lag_4', 'volume_lag_8',
    # Raw volume (current interval)
    'volume_15min',
]

df_model = df.dropna(subset=FEATURES + [TARGET]).copy()
print(f"\nRecords after dropping NaN: {len(df_model)}")


# ── 8. Time-Aware Train / Val / Test Split ───────────────────
# 70% train | 10% validation (for early stopping) | 20% test
# Strict time ordering — no shuffling

n = len(df_model)
sorted_df = df_model.sort_values('time_start').reset_index(drop=True)

train_end = int(n * 0.70)
val_end   = int(n * 0.80)

train_df = sorted_df.iloc[:train_end]
val_df   = sorted_df.iloc[train_end:val_end]
test_df  = sorted_df.iloc[val_end:]

print(f"\nTrain size: {len(train_df)}")
print(f"Val size:   {len(val_df)}")
print(f"Test size:  {len(test_df)}")
print(f"Train time range: {train_df['time_start'].min()} to {train_df['time_start'].max()}")
print(f"Test time range:  {test_df['time_start'].min()} to {test_df['time_start'].max()}")

X_train = train_df[FEATURES]
y_train = train_df[TARGET]
X_val   = val_df[FEATURES]
y_val   = val_df[TARGET]
X_test  = test_df[FEATURES]
y_test  = test_df[TARGET]


# ── 9. Train XGBoost ─────────────────────────────────────────
print("\nTraining XGBoost...")

xgb_model = XGBRegressor(
    n_estimators      = 1000,   # high ceiling — early stopping will cut this down
    learning_rate     = 0.05,
    max_depth         = 6,
    min_child_weight  = 5,
    subsample         = 0.8,    # row sampling per tree (reduces overfitting)
    colsample_bytree  = 0.8,    # feature sampling per tree
    reg_alpha         = 0.1,    # L1 regularization
    reg_lambda        = 1.0,    # L2 regularization
    random_state      = 42,
    n_jobs            = -1,
    tree_method       = 'hist', # fast histogram method — good for large datasets
    early_stopping_rounds = 30, # stop if val loss doesn't improve for 30 rounds
    eval_metric       = 'rmse',
)

xgb_model.fit(
    X_train, y_train,
    eval_set=[(X_val, y_val)],
    verbose=50,   # print every 50 rounds
)

print(f"\nBest iteration: {xgb_model.best_iteration}")


# ── 10. Evaluate ─────────────────────────────────────────────
y_pred = xgb_model.predict(X_test)

mae  = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2   = r2_score(y_test, y_pred)

print("\n===== XGBoost Model Performance =====")
print(f"MAE  : {mae:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"R^2  : {r2:.4f}")


# ── 11. Save Model & Predictions ─────────────────────────────
MODEL_PATH = '/content/drive/MyDrive/ECE1513_Project/Models/xgb_model.pkl'
joblib.dump(xgb_model, MODEL_PATH)
print(f"\nSaved model to {MODEL_PATH}")

preds_df = test_df[['centreline_id', 'direction', 'time_start', TARGET]].copy()
preds_df['predicted_speed'] = y_pred
preds_df.to_csv(
    '/content/drive/MyDrive/ECE1513_Project/Data/xgb_predictions.csv',
    index=False
)
print("Saved predictions to xgb_predictions.csv")


# ── 12. Feature Importance ───────────────────────────────────
importance_df = pd.DataFrame({
    'feature':    FEATURES,
    'importance': xgb_model.feature_importances_,
}).sort_values('importance', ascending=False)

print("\nTop 20 important features:")
print(importance_df.head(20).to_string())

importance_df.to_csv(
    '/content/drive/MyDrive/ECE1513_Project/Data/xgb_feature_importance.csv',
    index=False
)
print("\nSaved feature importance to xgb_feature_importance.csv")


# ── 13. Load & Reuse (example) ───────────────────────────────
# To reuse this model in any future notebook, just run:
#
#   import joblib
#   xgb_model = joblib.load('/content/drive/MyDrive/ECE1513_Project/Models/xgb_model.pkl')
#   y_pred = xgb_model.predict(X_test)

Mounted at /content/drive
Total records loaded: 1737739
Date range: 2020-01-14 00:00:00 to 2024-12-19 23:45:00

Records after dropping NaN: 1692667

Train size: 1184866
Val size:   169267
Test size:  338534
Train time range: 2020-01-14 02:00:00 to 2023-06-23 04:15:00
Test time range:  2023-11-02 16:00:00 to 2024-12-19 23:45:00

Training XGBoost...
[0]	validation_0-rmse:3.65864
[50]	validation_0-rmse:3.28051
[100]	validation_0-rmse:3.22866
[150]	validation_0-rmse:3.21056
[200]	validation_0-rmse:3.19934
[250]	validation_0-rmse:3.19194
[300]	validation_0-rmse:3.18453
[350]	validation_0-rmse:3.17855
[400]	validation_0-rmse:3.17360
[450]	validation_0-rmse:3.16975
[500]	validation_0-rmse:3.16735
[550]	validation_0-rmse:3.16509
[600]	validation_0-rmse:3.16207
[650]	validation_0-rmse:3.16049
[700]	validation_0-rmse:3.15947
[750]	validation_0-rmse:3.15755
[800]	validation_0-rmse:3.15627
[850]	validation_0-rmse:3.15506
[879]	validation_0-rmse:3.15519

Best iteration: 849

===== XGBoost Model Performance =====
MAE  : 2.2399
RMSE : 3.4153
R^2  : 0.2256

Saved model to /content/drive/MyDrive/ECE1513_Project/Models/xgb_model.pkl
Saved predictions to xgb_predictions.csv

Top 20 important features:
                   feature  importance
32   speed_dev_roll_mean_8    0.145837
31   speed_dev_roll_mean_4    0.056723
43            volume_15min    0.052884
23         speed_dev_lag_1    0.047183
22         hist_avg_volume    0.042816
36  volume_dev_roll_mean_8    0.036112
25         speed_dev_lag_4    0.032662
34    speed_dev_roll_std_8    0.032557
40            volume_lag_2    0.027749
1                 latitude    0.027581
9                  dow_sin    0.026272
41            volume_lag_4    0.022171
26         speed_dev_lag_8    0.021955
24         speed_dev_lag_2    0.021622
42            volume_lag_8    0.020103
21          hist_avg_speed    0.018846
0                longitude    0.018328
5                    month    0.018078
2            centreline_id    0.017023
35  volume_dev_roll_mean_4    0.017021

Saved feature importance to xgb_feature_importance.csv

In [ ]:
#before

# ============================================================
# ECE1513 Project — XGBoost Regression Model
# Improvements over RF baseline:
#   - Speed deviation feature (fixes leakage)
#   - Deviation-based lags & rolling stats
#   - XGBoost with early stopping
#   - Saves model with joblib
# ============================================================

import pandas as pd
import numpy as np
import joblib
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from google.colab import drive

# ── 1. Load Data ─────────────────────────────────────────────

drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/ECE1513_Project/Data/final_traffic_weather_ml_ready.csv'

df = pd.read_csv(file_path)
df['time_start'] = pd.to_datetime(df['time_start'])
df['time_end']   = pd.to_datetime(df['time_end'])
df = df.sort_values(['centreline_id', 'direction', 'time_start']).reset_index(drop=True)

print(f"Total records loaded: {len(df)}")
print(f"Date range: {df['time_start'].min()} to {df['time_start'].max()}")


# ── 2. Time Features ─────────────────────────────────────────
df['hour']       = df['time_start'].dt.hour
df['minute']     = df['time_start'].dt.minute
df['dayofweek']  = df['time_start'].dt.dayofweek
df['month']      = df['time_start'].dt.month
df['is_weekend'] = (df['dayofweek'] >= 5).astype(int)

df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)
df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)
df['dow_sin']  = np.sin(2 * np.pi * df['dayofweek'] / 7)
df['dow_cos']  = np.cos(2 * np.pi * df['dayofweek'] / 7)


# ── 3. Speed Deviation (leakage fix) ─────────────────────────
# For each road segment + direction + hour + day-of-week,
# compute the historical average speed. Then subtract it.
# This tells the model "is traffic abnormally slow RIGHT NOW?"
# instead of leaking the raw speed value directly into lags.

historical_avg = (
    df.groupby(['centreline_id', 'direction', 'hour', 'dayofweek'])['avg_speed_kph']
    .transform('mean')
)
df['speed_deviation'] = df['avg_speed_kph'] - historical_avg

# Same for volume
historical_vol_avg = (
    df.groupby(['centreline_id', 'direction', 'hour', 'dayofweek'])['volume_15min']
    .transform('mean')
)
df['volume_deviation'] = df['volume_15min'] - historical_vol_avg


# ── 4. Lag Features (on deviation, not raw speed) ────────────
group_keys = ['centreline_id', 'direction']

# Deviation lags — these are the safe, non-leaky version
for lag in [1, 2, 4, 8]:
    df[f'speed_dev_lag_{lag}']  = df.groupby(group_keys)['speed_deviation'].shift(lag)
    df[f'volume_dev_lag_{lag}'] = df.groupby(group_keys)['volume_deviation'].shift(lag)

# Keep raw speed lags too but with a larger minimum gap (lag >= 2)
# lag_1 of raw speed is fine as long as we don't also include roll_mean_1
for lag in [2, 4, 8]:
    df[f'speed_lag_{lag}']  = df.groupby(group_keys)['avg_speed_kph'].shift(lag)
    df[f'volume_lag_{lag}'] = df.groupby(group_keys)['volume_15min'].shift(lag)


# ── 5. Rolling Window Features (on deviation) ─────────────────
for window in [4, 8]:
    grp = df.groupby(group_keys)

    # Rolling mean of deviation — "has it been getting worse recently?"
    df[f'speed_dev_roll_mean_{window}'] = (
        grp['speed_deviation']
        .transform(lambda x: x.shift(1).rolling(window, min_periods=1).mean())
    )
    df[f'speed_dev_roll_std_{window}'] = (
        grp['speed_deviation']
        .transform(lambda x: x.shift(1).rolling(window, min_periods=1).std())
    )
    df[f'volume_dev_roll_mean_{window}'] = (
        grp['volume_deviation']
        .transform(lambda x: x.shift(1).rolling(window, min_periods=1).mean())
    )

    # Raw speed rolling (shifted by 2 to avoid leakage from t-1)
    df[f'speed_roll_mean_{window}'] = (
        grp['avg_speed_kph']
        .transform(lambda x: x.shift(2).rolling(window, min_periods=1).mean())
    )


# ── 6. Historical context features ───────────────────────────
# Give the model direct access to what "normal" looks like
# for this segment/hour/DOW combination
df['hist_avg_speed']  = historical_avg
df['hist_avg_volume'] = historical_vol_avg


# ── 7. Define Features & Target ──────────────────────────────
TARGET = 'speed_deviation'

FEATURES = [
    # Location
    'longitude', 'latitude', 'centreline_id',
    # Time
    'hour', 'dayofweek', 'month', 'is_weekend',
    'hour_sin', 'hour_cos', 'dow_sin', 'dow_cos',
    # Weather
    'Temp (°C)', 'Precip. Amount (mm)', 'Wind Spd (km/h)',
    'Visibility (km)', 'Rel Hum (%)',
    'Wind_Sin', 'Wind_Cos',
    'is_raining', 'is_snowing', 'is_foggy',
    # Historical context (what is "normal" here)
    'hist_avg_speed', 'hist_avg_volume',
    # Deviation lags (core non-leaky signal)
    'speed_dev_lag_1', 'speed_dev_lag_2', 'speed_dev_lag_4', 'speed_dev_lag_8',
    'volume_dev_lag_1', 'volume_dev_lag_2', 'volume_dev_lag_4', 'volume_dev_lag_8',
    # Deviation rolling stats
    'speed_dev_roll_mean_4', 'speed_dev_roll_mean_8',
    'speed_dev_roll_std_4',  'speed_dev_roll_std_8',
    'volume_dev_roll_mean_4', 'volume_dev_roll_mean_8',
    # Raw lags (lag >= 2 only)
    'speed_lag_2', 'speed_lag_4', 'speed_lag_8',
    'volume_lag_2', 'volume_lag_4', 'volume_lag_8',
    # Raw volume (current interval)
    'volume_15min',
]

df_model = df.dropna(subset=FEATURES + [TARGET]).copy()
print(f"\nRecords after dropping NaN: {len(df_model)}")


# ── 8. Time-Aware Train / Val / Test Split ───────────────────
# 70% train | 10% validation (for early stopping) | 20% test
# Strict time ordering — no shuffling

n = len(df_model)
sorted_df = df_model.sort_values('time_start').reset_index(drop=True)

train_end = int(n * 0.70)
val_end   = int(n * 0.80)

train_df = sorted_df.iloc[:train_end]
val_df   = sorted_df.iloc[train_end:val_end]
test_df  = sorted_df.iloc[val_end:]

print(f"\nTrain size: {len(train_df)}")
print(f"Val size:   {len(val_df)}")
print(f"Test size:  {len(test_df)}")
print(f"Train time range: {train_df['time_start'].min()} to {train_df['time_start'].max()}")
print(f"Test time range:  {test_df['time_start'].min()} to {test_df['time_start'].max()}")

X_train = train_df[FEATURES]
y_train = train_df[TARGET]
X_val   = val_df[FEATURES]
y_val   = val_df[TARGET]
X_test  = test_df[FEATURES]
y_test  = test_df[TARGET]


# ── 9. Train XGBoost ─────────────────────────────────────────
print("\nTraining XGBoost...")

xgb_model = XGBRegressor(
    n_estimators      = 1000,   # high ceiling — early stopping will cut this down
    learning_rate     = 0.05,
    max_depth         = 6,
    min_child_weight  = 5,
    subsample         = 0.8,    # row sampling per tree (reduces overfitting)
    colsample_bytree  = 0.8,    # feature sampling per tree
    reg_alpha         = 0.1,    # L1 regularization
    reg_lambda        = 1.0,    # L2 regularization
    random_state      = 42,
    n_jobs            = -1,
    tree_method       = 'hist', # fast histogram method — good for large datasets
    early_stopping_rounds = 30, # stop if val loss doesn't improve for 30 rounds
    eval_metric       = 'rmse',
)

xgb_model.fit(
    X_train, y_train,
    eval_set=[(X_val, y_val)],
    verbose=50,   # print every 50 rounds
)

print(f"\nBest iteration: {xgb_model.best_iteration}")


# ── 10. Evaluate ─────────────────────────────────────────────
y_pred = xgb_model.predict(X_test)

mae  = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2   = r2_score(y_test, y_pred)

print("\n===== XGBoost Model Performance =====")
print(f"MAE  : {mae:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"R^2  : {r2:.4f}")


# ── 11. Save Model & Predictions ─────────────────────────────
MODEL_PATH = '/content/drive/MyDrive/ECE1513_Project/Models/xgb_model.pkl'
joblib.dump(xgb_model, MODEL_PATH)
print(f"\nSaved model to {MODEL_PATH}")

preds_df = test_df[['centreline_id', 'direction', 'time_start', TARGET]].copy()
preds_df['predicted_speed'] = y_pred
preds_df.to_csv(
    '/content/drive/MyDrive/ECE1513_Project/Data/xgb_predictions.csv',
    index=False
)
print("Saved predictions to xgb_predictions.csv")


# ── 12. Feature Importance ───────────────────────────────────
importance_df = pd.DataFrame({
    'feature':    FEATURES,
    'importance': xgb_model.feature_importances_,
}).sort_values('importance', ascending=False)

print("\nTop 20 important features:")
print(importance_df.head(20).to_string())

importance_df.to_csv(
    '/content/drive/MyDrive/ECE1513_Project/Data/xgb_feature_importance.csv',
    index=False
)
print("\nSaved feature importance to xgb_feature_importance.csv")


# ── 13. Load & Reuse (example) ───────────────────────────────
# To reuse this model in any future notebook, just run:
#
#   import joblib
#   xgb_model = joblib.load('/content/drive/MyDrive/ECE1513_Project/Models/xgb_model.pkl')
#   y_pred = xgb_model.predict(X_test)

Mounted at /content/drive
Total records loaded: 1737739
Date range: 2020-01-14 00:00:00 to 2024-12-19 23:45:00

Records after dropping NaN: 1692667

Train size: 1184866
Val size:   169267
Test size:  338534
Train time range: 2020-01-14 02:00:00 to 2023-06-23 04:15:00
Test time range:  2023-11-02 16:00:00 to 2024-12-19 23:45:00

Training XGBoost...
[0]	validation_0-rmse:3.65864
[50]	validation_0-rmse:3.28051
[100]	validation_0-rmse:3.22866
[150]	validation_0-rmse:3.21056
[200]	validation_0-rmse:3.19934
[250]	validation_0-rmse:3.19194
[300]	validation_0-rmse:3.18453
[350]	validation_0-rmse:3.17855
[400]	validation_0-rmse:3.17360
[450]	validation_0-rmse:3.16975
[500]	validation_0-rmse:3.16735
[550]	validation_0-rmse:3.16509
[600]	validation_0-rmse:3.16207
[650]	validation_0-rmse:3.16049
[700]	validation_0-rmse:3.15947
[750]	validation_0-rmse:3.15755
[800]	validation_0-rmse:3.15627
[850]	validation_0-rmse:3.15506
[879]	validation_0-rmse:3.15519

Best iteration: 849

===== XGBoost Model Performance =====
MAE  : 2.2399
RMSE : 3.4153
R^2  : 0.2256

Saved model to /content/drive/MyDrive/ECE1513_Project/Models/xgb_model.pkl
Saved predictions to xgb_predictions.csv

Top 20 important features:
                   feature  importance
32   speed_dev_roll_mean_8    0.145837
31   speed_dev_roll_mean_4    0.056723
43            volume_15min    0.052884
23         speed_dev_lag_1    0.047183
22         hist_avg_volume    0.042816
36  volume_dev_roll_mean_8    0.036112
25         speed_dev_lag_4    0.032662
34    speed_dev_roll_std_8    0.032557
40            volume_lag_2    0.027749
1                 latitude    0.027581
9                  dow_sin    0.026272
41            volume_lag_4    0.022171
26         speed_dev_lag_8    0.021955
24         speed_dev_lag_2    0.021622
42            volume_lag_8    0.020103
21          hist_avg_speed    0.018846
0                longitude    0.018328
5                    month    0.018078
2            centreline_id    0.017023
35  volume_dev_roll_mean_4    0.017021

Saved feature importance to xgb_feature_importance.csv

In [ ]:
# This is the XGBoost regression model training block.
# ============================================================
# ECE1513 Project — XGBoost Regression Model
# Improvements over RF baseline:
#   - Speed deviation feature (fixes leakage)
#   - Deviation-based lags & rolling stats
#   - XGBoost with early stopping
#   - Saves model with joblib
# ============================================================

import pandas as pd
import numpy as np
import joblib
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from google.colab import drive

# ── 1. Load Data ─────────────────────────────────────────────

drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/ECE1513_Project/Data/final_traffic_weather_merged.csv'

df = pd.read_csv(file_path)
df['time_start'] = pd.to_datetime(df['time_start'])
df['time_end']   = pd.to_datetime(df['time_end'])
df = df.sort_values(['centreline_id', 'direction', 'time_start']).reset_index(drop=True)

print(f"Total records loaded: {len(df)}")
print(f"Date range: {df['time_start'].min()} to {df['time_start'].max()}")


# ── 2. Time Features ─────────────────────────────────────────
df['hour']       = df['time_start'].dt.hour
df['minute']     = df['time_start'].dt.minute
df['dayofweek']  = df['time_start'].dt.dayofweek
df['month']      = df['time_start'].dt.month
df['is_weekend'] = (df['dayofweek'] >= 5).astype(int)

df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)
df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)
df['dow_sin']  = np.sin(2 * np.pi * df['dayofweek'] / 7)
df['dow_cos']  = np.cos(2 * np.pi * df['dayofweek'] / 7)


# ── 3. Speed Deviation (leakage fix) ─────────────────────────
# For each road segment + direction + hour + day-of-week,
# compute the historical average speed. Then subtract it.
# This tells the model "is traffic abnormally slow RIGHT NOW?"
# instead of leaking the raw speed value directly into lags.

historical_avg = (
    df.groupby(['centreline_id', 'direction', 'hour', 'dayofweek'])['avg_speed_kph']
    .transform('mean')
)
df['speed_deviation'] = df['avg_speed_kph'] - historical_avg

# Same for volume
historical_vol_avg = (
    df.groupby(['centreline_id', 'direction', 'hour', 'dayofweek'])['volume_15min']
    .transform('mean')
)
df['volume_deviation'] = df['volume_15min'] - historical_vol_avg


# ── 4. Lag Features (on deviation, not raw speed) ────────────
group_keys = ['centreline_id', 'direction']

# Deviation lags — these are the safe, non-leaky version
for lag in [1, 2, 4, 8]:
    df[f'speed_dev_lag_{lag}']  = df.groupby(group_keys)['speed_deviation'].shift(lag)
    df[f'volume_dev_lag_{lag}'] = df.groupby(group_keys)['volume_deviation'].shift(lag)

# Keep raw speed lags too but with a larger minimum gap (lag >= 2)
# lag_1 of raw speed is fine as long as we don't also include roll_mean_1
for lag in [2, 4, 8]:
    df[f'speed_lag_{lag}']  = df.groupby(group_keys)['avg_speed_kph'].shift(lag)
    df[f'volume_lag_{lag}'] = df.groupby(group_keys)['volume_15min'].shift(lag)


# ── 5. Rolling Window Features (on deviation) ─────────────────
for window in [4, 8]:
    grp = df.groupby(group_keys)

    # Rolling mean of deviation — "has it been getting worse recently?"
    df[f'speed_dev_roll_mean_{window}'] = (
        grp['speed_deviation']
        .transform(lambda x: x.shift(1).rolling(window, min_periods=1).mean())
    )
    df[f'speed_dev_roll_std_{window}'] = (
        grp['speed_deviation']
        .transform(lambda x: x.shift(1).rolling(window, min_periods=1).std())
    )
    df[f'volume_dev_roll_mean_{window}'] = (
        grp['volume_deviation']
        .transform(lambda x: x.shift(1).rolling(window, min_periods=1).mean())
    )

    # Raw speed rolling (shifted by 2 to avoid leakage from t-1)
    df[f'speed_roll_mean_{window}'] = (
        grp['avg_speed_kph']
        .transform(lambda x: x.shift(2).rolling(window, min_periods=1).mean())
    )


# ── 6. Historical context features ───────────────────────────
# Give the model direct access to what "normal" looks like
# for this segment/hour/DOW combination
df['hist_avg_speed']  = historical_avg
df['hist_avg_volume'] = historical_vol_avg


# ── 7. Define Features & Target ──────────────────────────────
TARGET = 'avg_speed_kph'

FEATURES = [
    # Location
    'longitude', 'latitude', 'centreline_id',
    # Time
    'hour', 'dayofweek', 'month', 'is_weekend',
    'hour_sin', 'hour_cos', 'dow_sin', 'dow_cos',
    # Weather
    'Temp (°C)', 'Precip. Amount (mm)', 'Wind Spd (km/h)',
    'Visibility (km)', 'Rel Hum (%)',
    'Wind_Sin', 'Wind_Cos',
    'is_raining', 'is_snowing', 'is_foggy',
    # Historical context (what is "normal" here)
    'hist_avg_speed', 'hist_avg_volume',
    # Deviation lags (core non-leaky signal)
    'speed_dev_lag_1', 'speed_dev_lag_2', 'speed_dev_lag_4', 'speed_dev_lag_8',
    'volume_dev_lag_1', 'volume_dev_lag_2', 'volume_dev_lag_4', 'volume_dev_lag_8',
    # Deviation rolling stats
    'speed_dev_roll_mean_4', 'speed_dev_roll_mean_8',
    'speed_dev_roll_std_4',  'speed_dev_roll_std_8',
    'volume_dev_roll_mean_4', 'volume_dev_roll_mean_8',
    # Raw lags (lag >= 2 only)
    'speed_lag_2', 'speed_lag_4', 'speed_lag_8',
    'volume_lag_2', 'volume_lag_4', 'volume_lag_8',
    # Raw rolling (shifted by 2)
    'speed_roll_mean_4', 'speed_roll_mean_8',
    # Raw volume (current interval)
    'volume_15min',
]

df_model = df.dropna(subset=FEATURES + [TARGET]).copy()
print(f"\nRecords after dropping NaN: {len(df_model)}")


# ── 8. Time-Aware Train / Val / Test Split ───────────────────
# 70% train | 10% validation (for early stopping) | 20% test
# Strict time ordering — no shuffling

n = len(df_model)
sorted_df = df_model.sort_values('time_start').reset_index(drop=True)

train_end = int(n * 0.70)
val_end   = int(n * 0.80)

train_df = sorted_df.iloc[:train_end]
val_df   = sorted_df.iloc[train_end:val_end]
test_df  = sorted_df.iloc[val_end:]

print(f"\nTrain size: {len(train_df)}")
print(f"Val size:   {len(val_df)}")
print(f"Test size:  {len(test_df)}")
print(f"Train time range: {train_df['time_start'].min()} to {train_df['time_start'].max()}")
print(f"Test time range:  {test_df['time_start'].min()} to {test_df['time_start'].max()}")

X_train = train_df[FEATURES]
y_train = train_df[TARGET]
X_val   = val_df[FEATURES]
y_val   = val_df[TARGET]
X_test  = test_df[FEATURES]
y_test  = test_df[TARGET]


# ── 9. Train XGBoost ─────────────────────────────────────────
print("\nTraining XGBoost...")

xgb_model = XGBRegressor(
    n_estimators      = 1000,   # high ceiling — early stopping will cut this down
    learning_rate     = 0.05,
    max_depth         = 6,
    min_child_weight  = 5,
    subsample         = 0.8,    # row sampling per tree (reduces overfitting)
    colsample_bytree  = 0.8,    # feature sampling per tree
    reg_alpha         = 0.1,    # L1 regularization
    reg_lambda        = 1.0,    # L2 regularization
    random_state      = 42,
    n_jobs            = -1,
    tree_method       = 'hist', # fast histogram method — good for large datasets
    early_stopping_rounds = 30, # stop if val loss doesn't improve for 30 rounds
    eval_metric       = 'rmse',
)

xgb_model.fit(
    X_train, y_train,
    eval_set=[(X_val, y_val)],
    verbose=50,   # print every 50 rounds
)

print(f"\nBest iteration: {xgb_model.best_iteration}")


# ── 10. Evaluate ─────────────────────────────────────────────
y_pred = xgb_model.predict(X_test)

mae  = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2   = r2_score(y_test, y_pred)

print("\n===== XGBoost Model Performance =====")
print(f"MAE  : {mae:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"R^2  : {r2:.4f}")


# ── 11. Save Model & Predictions ─────────────────────────────
MODEL_PATH = '/content/drive/MyDrive/ECE1513_Project/Models/xgb_model.pkl'
joblib.dump(xgb_model, MODEL_PATH)
print(f"\nSaved model to {MODEL_PATH}")

preds_df = test_df[['centreline_id', 'direction', 'time_start', TARGET]].copy()
preds_df['predicted_speed'] = y_pred
preds_df.to_csv(
    '/content/drive/MyDrive/ECE1513_Project/Data/xgb_predictions.csv',
    index=False
)
print("Saved predictions to xgb_predictions.csv")


# ── 12. Feature Importance ───────────────────────────────────
importance_df = pd.DataFrame({
    'feature':    FEATURES,
    'importance': xgb_model.feature_importances_,
}).sort_values('importance', ascending=False)

print("\nTop 20 important features:")
print(importance_df.head(20).to_string())

importance_df.to_csv(
    '/content/drive/MyDrive/ECE1513_Project/Data/xgb_feature_importance.csv',
    index=False
)
print("\nSaved feature importance to xgb_feature_importance.csv")


# ── 13. Load & Reuse (example) ───────────────────────────────
# To reuse this model in any future notebook, just run:
#
#   import joblib
#   xgb_model = joblib.load('/content/drive/MyDrive/ECE1513_Project/Models/xgb_model.pkl')
#   y_pred = xgb_model.predict(X_test)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Total records loaded: 1737739
Date range: 2020-01-14 00:00:00 to 2024-12-19 23:45:00

Records after dropping NaN: 1692667

Train size: 1184866
Val size:   169267
Test size:  338534
Train time range: 2020-01-14 02:00:00 to 2023-06-23 04:15:00
Test time range:  2023-11-02 16:00:00 to 2024-12-19 23:45:00

Training XGBoost...
[0]	validation_0-rmse:10.88187
[50]	validation_0-rmse:3.58241
[100]	validation_0-rmse:3.32183
[150]	validation_0-rmse:3.25391
[200]	validation_0-rmse:3.22942
[250]	validation_0-rmse:3.21475
[300]	validation_0-rmse:3.20439
[350]	validation_0-rmse:3.19578
[400]	validation_0-rmse:3.18979
[450]	validation_0-rmse:3.18481
[500]	validation_0-rmse:3.18072
[550]	validation_0-rmse:3.17773
[600]	validation_0-rmse:3.17587
[650]	validation_0-rmse:3.17319
[700]	validation_0-rmse:3.17069
[750]	validation_0-rmse:3.16854
[800]	validation_0-rmse:3.16722
[850]	validation_0-rmse:3.16570
[900]	validation_0-rmse:3.16462
[950]	validation_0-rmse:3.16342
[999]	validation_0-rmse:3.16230

Best iteration: 996

===== XGBoost Model Performance =====
MAE  : 2.2459
RMSE : 3.4191
R^2  : 0.8910

Saved model to /content/drive/MyDrive/ECE1513_Project/Models/xgb_model.pkl
Saved predictions to xgb_predictions.csv

Top 20 important features:
                   feature  importance
21          hist_avg_speed    0.678652
44       speed_roll_mean_8    0.188056
37             speed_lag_2    0.038395
38             speed_lag_4    0.019084
32   speed_dev_roll_mean_8    0.007606
43       speed_roll_mean_4    0.005337
45            volume_15min    0.004357
31   speed_dev_roll_mean_4    0.003909
22         hist_avg_volume    0.003207
23         speed_dev_lag_1    0.002856
36  volume_dev_roll_mean_8    0.002752
39             speed_lag_8    0.002642
24         speed_dev_lag_2    0.002336
1                 latitude    0.002079
25         speed_dev_lag_4    0.002052
0                longitude    0.001978
40            volume_lag_2    0.001974
41            volume_lag_4    0.001831
5                    month    0.001609
26         speed_dev_lag_8    0.001588

Saved feature importance to xgb_feature_importance.csv